### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by xsnrg** [cdjackson/HABmin2#1]
Greetings,  I have installed the latest snapshot of openhab2 and am trying to install Habmin2 following the directions in the readme here on github.  When I go to the URL, I get a 404 which is probably telling me I have not dropped the exploded zip file in the correct place in the folder structure, or am missing other files.  Where in the tree should "webapps" exist?

**Comment by xsnrg** [comment]
Happy New Year, any OH2 updates?

**Comment by cdjackson** [comment]
Hi, and happy new year…

Not specifically. I’ve been working on getting the code ironed out in general, and making it work reasonably well on my mobile phone (i.e. more responsive). I‘ll probably start to look at OH2 in a few days.

**Comment by HakanP** [comment]
Any hardcoded paths or other requirements for Habmin2 than habmin? Can run that without any problem, but if I try the test-release of habmin2 I just get an empty interface of it, no sitemaps, items or z-wave at all. Running it on a RPi and have it installed in an own directory for the user.

**Comment by cdjackson** [comment]
All paths are relative (but hardcoded obviously) to the server. It uses the same rest interfaces as HABmin.
Are you using security or anything?

**Comment by HakanP** [comment]
No, nothing special. Looks like this:
![habmin](https://cloud.githubusercontent.com/assets/10425282/5665435/b2c2547e-9758-11e4-860a-15c7e570787a.PNG)
![habmin_zwave](https://cloud.githubusercontent.com/assets/10425282/5665432/b2b94898-9758-11e4-8e89-2a1587d4f345.PNG)
![habmin2](https://cloud.githubusercontent.com/assets/10425282/5665434/b2c13620-9758-11e4-827d-0cc0d26da3c8.PNG)
![habmin2_zwave](https://cloud.githubusercontent.com/assets/10425282/5665433/b2beba94-9758-11e4-84b2-1328f620a801.PNG)

**Comment by cdjackson** [comment]
Strange. It looks like you’re using Chrome - can you enable developers tools (just click on the menu in the top right, go to More Tools, then Developers Tools) and see if tat shows any errors or warnings?=

**Comment by krumpaul** [comment]
im getting the same issue after install with habmin2 here is the dev tools.  no security as this is a test install running demo  "10.100.5.33:8080/rest/sitemaps/"  works and is correct.  it tries to connect to "10.100.5.33:8080/rest/sitemaps//"

![image](https://cloud.githubusercontent.com/assets/10473698/5690832/4586c0be-9863-11e4-9ef7-93f08b2ceea9.png)

**Comment by cdjackson** [comment]
Strange - is this when you first open HABmin? When HABmin starts, it should request a list of sitemaps, and if this is what you’re showing me, it’s quite strange where the // is coming from. The code in question is -:

this.url = UserService.getServer() + '/rest/sitemaps';
this.socket = null;
this.getList = function () {
    var deferred = $q.defer();
    $http.get(this.url).success(function (data, status) {

So I’m not sure why it would put the // on the end of the url. Or, is this later - e.g. when you try and actually load a sitemap?

**Comment by HakanP** [comment]
If I try to create a new sitemap I get a similar response:
Remote Address:192.168.0.251:8080
Request URL:http://192.168.0.251:8080/rest/sitemaps//
Request Method:GET
Status Code:404 Not Found
Request Headersview source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:sv-SE,sv;q=0.8,en-US;q=0.6,en;q=0.4
Authorization:
Connection:keep-alive
Cookie:ext-automationWindowSizer=o%3A; ext-configWindowSizer=o%3Awidth%3Dn%253A455; ext-graphWindowSizer=o%3A
Host:192.168.0.251:8080
Referer:http://192.168.0.251:8080/habmin2/
User-Agent:Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
Response Headersview source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:*
Cache-Control:must-revalidate,no-cache,no-store
Content-Length:1380
Content-Type:text/html;charset=ISO-8859-1
Date:Sat, 10 Jan 2015 11:00:12 GMT
Pragma:no-cache
Server:Jetty(8.1.3.v20120522)
X-Atmosphere-tracking-id:ba658a74-cf5f-49fe-9e22-e7bf60e6664b


And also some other files missing.
![habmin2_errors](https://cloud.githubusercontent.com/assets/10425282/5691373/64ff1a4e-98c3-11e4-80e6-77eaad046037.PNG)

**Comment by cdjackson** [comment]
> 
> If I try to create a new sitemap I get a similar response:
> 
Ok - now I’m confused.
Can you please tell me exactly when this error is displayed (i.e. the original error you mentioned). The software does not allow creating sitemaps at the moment, so this will give the error. What I want to know is if the original error (wit the two //) was generated on startup, or do you get a list of sitemaps when the software starts, but then when you click on a sitemap you get the error?=

**Comment by HakanP** [comment]
No, don't see any sitemaps (only have one, default)

**Comment by cdjackson** [comment]
Ok - thanks. That’s strange - I’ll have to have a think about what might cause this as it shouldn’t change…

**Comment by HakanP** [comment]
What about the z-wave, should that be under the configurations-menu? At least I think I have seen it there the first time I started habmin2, but never again.

**Comment by cdjackson** [comment]
yes - you should have a “zwave configuration” menu item under the configuration menu. Is that not there either? This is added following a call to a rest endpoint "/bindings”. If you look in the NETWORK tab in Firebug (or chrome - whatever your using) what does it show (it should simply say ‘bindings’ - it’s probably right underneath, sitemaps)? Is it also red (I guess not as it’s not listed in errors). If you click on this entry in the network transactions tab, it should show you the returned data.

**Comment by HakanP** [comment]
If I do a full refresh on the main page Everything under Network-tab says OK. And there is one file for z-wave. 
![habmin2_1](https://cloud.githubusercontent.com/assets/10425282/5691528/69594d00-98cb-11e4-89a6-a988459b21b5.PNG)

Can start a teamviewer session if you wanna have a look for yourself.

**Comment by cdjackson** [comment]
No - that’s not the right place - it should be right at the bottom… It will say ‘bindings’ and won’t have the js extension…

I’m not familiar with TeamViewer, but that might be an interesting idea… Do I need to install anything here?

**Comment by HakanP** [comment]
You can just run the teamviwer exe-file without installing anything. I'm running version 9 so get it from this page: http://www.teamviewer.com/en/download/dyngate.aspx  (V10 is the latest).
I'll send you an email with the Connection-info.

**Comment by cdjackson** [comment]
Ok - thnaks. I’ve just downloaded the app…

**Comment by cdjackson** [comment]
Ok - just to confirm what we found. Firstly, you need to log on - or at least go through the login screen.
I'll look to fix this, but it's something that was needed. This got things working - zwave was then displayed.
After this, the next problem was a bug if there's only 1 sitemap in the system. I've fixed this and will
load an update shortly.

**Comment by anton101101** [comment]
Hey Chris,

I seem to be having a similar problem well I think it could be related or just me being an idiot an missing something, see the screenshot below:

![](http://i.gyazo.com/8960fc4b2b1cde9e26e12a1e242ebaee.png)

Also when I had the authentication set for OH so it prompted for a login, it would constantly pop-up with the authentication box whenever I went to /habmin2.  Now with the authentication off the result is the screenshot above. 


Thanks for your input in advance and for a great tool.

**Comment by cdjackson** [comment]
If youve changed from using authentication to not udint it, you may need to log ou and back in again. Otherwise habmin is probably still sending authentication headers.


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: anton101101 <notifications@github.com> </div><div>Date:11/01/2015  06:35  (GMT+00:00) </div><div>To: cdjackson/HABmin2 <HABmin2@noreply.github.com> </div><div>Cc: Chris Jackson <chris@cd-jackson.com> </div><div>Subject: Re: [HABmin2] Installation question (#1) </div><div>
</div>Hey Chris,

I seem to be having a similar problem well I think it could be related or just me being an idiot an missing something, see the screenshot below:



Also when I had the authentication set for OH so it prompted for a login, it would constantly pop-up with the authentication box whenever I went to /habmin2. Now with the authentication off the result is the screenshot above.

Thanks for your input in advance and for a great tool.

**Comment by xsnrg** [comment]
Given Habmin2 no longer supports serving webapps, I was wondering if the mobile version of Habmin2 would work with OpenHAB2, or at least be an easier route than trying to get an appserver running to be the equivalent of OpenHAB 1 serving /webapps ?

**Comment by cdjackson** [comment]
Sorry - I missed this. Openhab2 does support webapps - just a little differently than openhab1.

I'm currently working on an OH2 version and currently have a few services running. Once I get charting working and tested I'll likely make it available. I think I'll do that tonight as it looked like it was mostly working last night.

The mobile version is an option as well - both are about the same really, and currently both use the same source...

**Comment by xsnrg** [comment]
Greetings,  I pulled down .8 tonight and gave it a go.  I get this in the logs:

openhab.log:17:08:52.322 [INFO ] [u.h.internal.servlet.HABminApp:31   ] - Started HABmin servlet at /habmin
openhab.log:17:08:55.028 [WARN ] [assfish.jersey.internal.Errors:191  ] - The following warnings have been detected: WARNING: The (sub)resource method httpGetPersistenceCharts in org.openhab.ui.habmin.internal.services.chart.ChartResource contains empty path annotation.
openhab.log:WARNING: The (sub)resource method httpPostPersistenceCharts in org.openhab.ui.habmin.internal.services.chart.ChartResource contains empty path annotation.
openhab.log:WARNING: The (sub)resource method httpGetPersistenceServices in org.openhab.ui.habmin.internal.services.persistence.PersistenceResource contains empty path annotation.

When I go to 8080/habmin, I see a blank page.  Any pointers you have would be appreciated.

Thanks!

**Comment by cdjackson** [comment]
For some reason that is OH2 specific,  you need to add /index.html on the end of the url.

Ive seen the annotation error. Im not sure why it's there as all resources have a path so I need to look at this again, but it doesn't seem to stop anything working. 


Sent from Samsung Mobile

**Comment by xsnrg** [comment]
Thanks for that.  Adding index.html did indeed bring up the interface.  I was able to pull up an existing rule file as well as create a new one using the gui tool.  Very nice.  Thing configuration brings up the list of OH2 defined things, but items is empty other than the rules.  That is, Automation -> rules takes me to the same place as Configuration -> Items.

Should the zwave editor show up if the 1.7 zwave binding is loaded, or is there more to do for that?

Thanks, and let me know if there are areas you want tested.

Jim

**Comment by cdjackson** [comment]
> Thanks for that. Adding index.html did indeed bring up the interface. I was able to pull up an existing rule file as well as create a new one using the gui tool. Very nice. Thing configuration brings up the list of OH2 defined things, but items is empty other than the rules. That is, Automation -> rules takes me to the same place as Configuration -> Items.
> 
Yes - I haven’t implemented the items interface yet and it’s just linked to rules - I should remove this! :)

> Should the zwave editor show up if the 1.7 zwave binding is loaded, or is there more to do for that?
> 
No - it won’t show. I’m not sure if I can easily get this working - I’m in two minds - either to try and implement the current interface that works with the 1.7 binding, or port the binding to OH2. If I can clarify a few issues about thing generation, I’d probably prefer to port to OH2 and have a native binding.

> Thanks, and let me know if there are areas you want tested.
> 
Thanks.

**Comment by frostyandy2k** [comment]
Regarding the problem @xsnrg brought up (/index.html append required to URL). 
@cdjackson Could you update the installation tutorial with the correct URL
<code>Then open the browser at http://openhab server/habmin/index.html</code>
As it incorrectly gives a URL that does not work "Then open the browser at http://openhab server/habmin2."

**Comment by cdjackson** [comment]
I'll change the doc - the current doc is correct for OH1, but incorrect for OH2 (which I only added support for last week).

**Comment by frostyandy2k** [comment]
Thank you, and by the way: very nice job!

**Comment by cdjackson** [comment]
I'm going to close this issue - if there are still problems, please feel free to open a new issue...
