### ISSUE TITLE
Log viewer - is there any place where I can provide log path for OpenHAB?

### ISSUE THREAD

**Issue by grzech1983** [cdjackson/HABmin2#10]
Hello,

I always wanted to report it or ask about it (I don't see any logs in habmin1 too). Is there a special place where I can provide log directory (they are stored in /opt/openhab/logs)?

Regards

**Comment by cdjackson** [comment]
I'm not completely sure what you're asking. The Log Viewer is used to display the zwave logs, and to interpret them to provide feedback on the system etc. So, do you mean that you want a default directory from which to load these logs?

Or, are you asking about logging data FROM habmin into a directory somewhere?  If it's this, then HABmin errors etc are logged into the openhab log in the same way as other binding information...

Please can you clarify?

**Comment by grzech1983** [comment]
I'm asking about displaying current log content directly in habmin. Is there any place in documentation telling about it? As long as I remember I didn't had any logs content displayed there. Maybe I should change some params in logging configuration?

**Comment by cdjackson** [comment]
No - this isn’t possible - sorry.

**Comment by grzech1983** [comment]
Ah. Ok. No problem I just misunderstood this part functinality then.

**Comment by cdjackson** [comment]
A general log viewer was something I'd hoped to have in HABmin, but it's not so simple unfortunately... The zwave viewer is more than just a log display - it's a data processor that looks for problems in the network as well as showing what messages are being sent...

**Comment by grzech1983** [comment]
Ok but how it works exatly? Should I upload zwave log to it to see anything?

**Comment by cdjackson** [comment]
Yes - you need to upload the log file. Select the log with the "Select File" button, then the log will be processed and it will display an annotated version of the log. It also has a button called NODES - if you click on this it will provide some information on what it thinks is happening with the node.

It's still work in progress - currently I'm adding to it quite often as I look over someones log file and find an error. The idea being that as this expands, it will be quicker for me to look over peoples logs to find problems, but also, users should be able to process their own log and get some useful information on what their network is doing...

(that's the idea anyway :) )
