### ISSUE TITLE
Control Group widget does not work with OpenHAB 1

### ISSUE THREAD

**Issue by TheNetStriker** [cdjackson/HABmin2#100]
I've tried to configure a Control Group widget in HABmin2 on OpenHAB 1, but HABmin does not save the group item name in the dashboards.xml file. I've tried to add the group manually by adding <group>MyGroup</group> to the options in the xml, but then I get the following error when loading the dashboard:

com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$UnknownFieldException: No such field org.openhab.io.habmin.services.dashboard.DashboardWidgetOptionsBean.group

How can this be fixed?

**Comment by cdjackson** [comment]
Closing this since OH1 is no longer supported in HABmin2 (sorry)
