### ISSUE TITLE
z-wave configuration parameter drop down selector does not work

### ISSUE THREAD

**Issue by xsnrg** [cdjackson/HABmin2#102]
In the z-wave management area, click Configuration Parameters for the device on the right side.  Elements that are free-form entry can be modified.  Elements that are pre-defined selectors show a drop down.  Upon clicking the drop down, the element list is empty.

I see this behaviour for all devices I have looked at.  Here are some examples:

DSB06 - 80: Automatic notifications
DSB54 - 1: Send sensor binary report, 3: Send basic set on open/close
ZW096 - 3:  Current overload protection enable
DSB45 - 1: 2: 3: 
ZW20R - 1: Toggle LED mode

The default values or current settings also do not show in these elements.  I have tried this in Firefox, Chrome, and the mobile Habmin app.

![empty](https://cloud.githubusercontent.com/assets/1186921/11324279/ec9821b2-90f2-11e5-894e-6919964dc7b7.png)

**Comment by cdjackson** [comment]
This will all change completely when the OH2 binding is released…

**Comment by shorty707** [comment]
And that will be released approx....when? :-)

**Comment by cdjackson** [comment]
Well, I hope very soon (i.e. a few weeks).

**Comment by xsnrg** [comment]
@cdjackson , while we are waiting "two weeks" ;) if this is an easy one, it would be nice to be able to configure some of these devices.

I was following the thread on the ESH forum, but it seems to have dried up, is there still progress being made in another thread on how the dynamic stuff will be solved so you can release the 2.0 binding?  Can you link to the current discussion?

Thanks Chris

**Comment by cdjackson** [comment]
Yes - I created a PR for it last weekend and I think everyone is (finally :) ) happy. I need to create a test case and add that to the PR, then it’s done and we should be in business. I’ll try and do that this week…

Can you PM me on the forum (or email direct - I think you have my address).
