### ISSUE TITLE
Charts problem

### ISSUE THREAD

**Issue by tiithe** [cdjackson/HABmin2#103]
I have an issue with charts -- if I need to check smaller or larger time period (I "zoom" the chart in or out) then the charts are going  very rough (spikes and curves at random places) and it's going worse if I continue zooming / scrolling back or forward. First I though that it is my browsers problem (I use Opera), but it is same in every browser.

![chart](https://cloud.githubusercontent.com/assets/14896121/11346419/3cdb73f8-9225-11e5-8516-57e776993922.jpg)

All charts, in the picture, were sinuses, before I zoomed in.

**Comment by tiithe** [comment]
I think, it's related to rrd4j. I changed persistence to mysql and it seems to be OK now. Of course not too much data is collected, rrd4j had several months of data from 6 temperature sensors.
I use Openhab2 (compiled in October, as I remember).

**Comment by tiithe** [comment]
No .. same funky curves and knots are back, if data grows.

![charts](https://cloud.githubusercontent.com/assets/14896121/11526473/6366a186-98e3-11e5-8075-bc6624227a9c.jpg)

**Comment by cdjackson** [comment]
This isn't an issue with HABmin I think. It's more likely to be associated with the data - if there are glitches on the data, then HABmin will also graph these glitches.

**Comment by cdjackson** [comment]
Closing as I believe HABmin is just graphing the data it receives from OH.
