### ISSUE TITLE
Android app problem [offline message]

### ISSUE THREAD

**Issue by tiithe** [cdjackson/HABmin2#104]
Can you change the notification about server off-line status, not to be full screen. I can't find a way to  bypass it. Mostly annoys it, if I type in wrong server address... I can't then change it to right, because before I end editing, comes "Server Offline" message and the app is locked for me.

**Comment by stefanradike** [comment]
Yes please, it makes it different for me as well to find the correct settings. Actually, I haven't found it at all.
@cdjackson What is the correct server URL? I tried HOST:PORT, http://HOST:PORT/ and http://HOST:PORT/habmin/index.html and so far, nothing works. The WebApp is running fine, though.
