### ISSUE TITLE
Error loading data.

### ISSUE THREAD

**Issue by Br3nda** [cdjackson/HABmin2#106]
I had habmin2 working reading from mysql persistence happily

Yesterday I added myopenhab persistence, and habmin2 now displays error when trying to view a chart - It finds the items, but displays an error whenever i put on a chart, e.g.:
"Error loading data for item Arduino_kitchenmoisture"

Looking at the javascript console i can see this url has an 404 error
http://10.1.1.56:8080/services/habmin/persistence/services/myopenhab/Arduino_kitchenmoisture?endtime=1448963636209&starttime=1448877236209 

If I change the "myopenhab" portion of the url to "mysql", i get lots of good looking xml data. Not sure how to convince habmin2 to read that instead.

I've tried deleting the myopenhab.persistence file, and restarting the reloading - but habmin2 no longer display charts

Please, how do i get it back to working?

running Openhab 1.7 official dist release

**Comment by cdjackson** [comment]
You need to change the persistence source to mysql. This is one of the dropdown buttons in the chart window.

**Comment by Br3nda** [comment]
Thanks ! :-)
