### ISSUE TITLE
networkReplicate()

### ISSUE THREAD

**Issue by binladin** [cdjackson/HABmin2#108]
Hello Chris!

I began my acquaintance with OpenHab&Habmin2  with attempts to copy an existing zwave network from remote controler Remotec ZRC-100. But i found what Habmin2 src (zwave.js) don't contain functions  networkReplicate (), and replication of the primary network controller does not operate. Is it possible to improve the situation?

Leonid

**Comment by cdjackson** [comment]
Hi,
No - this isn’t currently implemented - sorry.

Chris
