### ISSUE TITLE
Z-wave binding: Please add Qubino DIN dimmer

### ISSUE THREAD

**Issue by dloeckx** [cdjackson/HABmin2#110]
Please find attached an xml file for the new Qubino DIN dimmer (ZMNHSD). Could you please add it to the repo?
The device is shown in HABmin as ID:52, type 1.
- xml-file: [zmnhsd.xml.zip](https://github.com/cdjackson/HABmin2/files/86640/zmnhsd.xml.zip)
- Documentation: https://www.intellihome.be/en/productattachments/index/download?id=1891

**Comment by cdjackson** [comment]
Thanks - I'll try and add this later today.

**Comment by cdjackson** [comment]
This should be in tomorrows snapshot.

**Comment by cdjackson** [comment]
I believe this is fixed, but if this is still an issue, please re-open.

**Comment by djfopenhab** [comment]
Hi, hope you can help. I know this is an old closed topic, and I can open a new thread if needed, but the zwave database is no longer showing these devices. 

I have several of these and have installed a fresh copy of OH2/HABMIN2 and they are showing as unknown devices. I tried OH2 about 6 weeks ago and checked the database then and it was there but showing a spanner. Now its missing completely from the list. 

I can assist in uploading any files / xml and and making changes to help get this device a permanent feature.

Many thanks
Dave

**Comment by cdjackson** [comment]
Hi Dave,
The database has been temporarily removed for this device - it will be added back in again in the next day or so. Someone found that it had a lot of errors, so we're going to regenerate it...

Stay tuned - it'll be back :)

Cheers
Chris

**Comment by djfopenhab** [comment]
Wow that was quick!
Thanks Chris, can I do anything to help ?

Sorry for the change of email address, I use aliases on all websites
