### ISSUE TITLE
please add fibaro roller shutter 2 fgr-222 (new version)

### ISSUE THREAD

**Issue by Gilles76** [cdjackson/HABmin2#112]
Hi Chris,

Hope you're fine.

I install a new version Fibaro roller shutter for a friend but it's not in database.

It's an EU version 2.5.

id=1000, type=302

![doc_fgr222](https://cloud.githubusercontent.com/assets/7738873/12397253/6e89fe7a-be0c-11e5-9d9c-3689c744b030.jpg)

Same function as fgr 222 just the external device appearance change.

Cheers,

Gilles.

**Comment by cdjackson** [comment]
Hi Gilles,
Is it possible to get the nodeX.xml file for this device?

Cheers
Chris

**Comment by Gilles76** [comment]
Hi Chris,

Hey happy New year !

It's not easy as my friend hasn't got internet but I will go and get the file. It's better to get it.

Cheers,

Gilles 



Le 19 janvier 2016 00:16:13 CET, Chris Jackson <notifications@github.com> a écrit :
>Hi Gilles,
>Is it possible to get the nodeX.xml file for this device?
>
>Cheers
>Chris
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cdjackson/HABmin2/issues/112#issuecomment-172678598

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by Gilles76** [comment]
Hi Chris,

OK, I've got the node file.

I send it to you by mail.

Cheers,

Gilles.

**Comment by cdjackson** [comment]
Thanks Gilles - I'll try and do this over the next few days.

**Comment by Gilles76** [comment]
Thank you Chris. 

Le 20 janvier 2016 23:53:33 GMT+01:00, Chris Jackson <notifications@github.com> a écrit :
>Thanks Gilles - I'll try and do this over the next few days.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cdjackson/HABmin2/issues/112#issuecomment-173389817

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by ghostreader86** [comment]
I guess this was already done in 1.8 https://github.com/openhab/openhab/pull/3665

**Comment by Gilles76** [comment]
Hi Chris,  ghostreader86, 
Could you confirm it's OK for last 1.8  snapshot? As my friend has got a 1.7. 
Thank you, 
Gilles 

Le 24 janvier 2016 21:31:03 GMT+01:00, ghostreader86 <notifications@github.com> a écrit :
>I guess this was already done in 1.8
>https://github.com/openhab/openhab/pull/3665
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cdjackson/HABmin2/issues/112#issuecomment-174339000

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by cdjackson** [comment]
Hi Gilles,
This was merged before 1.8 was released, so yes, it will be in 1.8.

Chris

**Comment by ghostreader86** [comment]
It is and it is working

**Comment by shrikantlahase** [comment]
Hi,
 
I have fgr 222 rollershutter and its not accepting UP DOWN STOP command in openhab 1.8.2 , its only accepting 0,99 values

Please anybody have solution for this...


Thanks
Shrikant

**Comment by cdjackson** [comment]
ZWave doesn’t have the concept of start/stop - just setting the position. Or maybe there’s a command class I’ve missed to do this with the new version?

**Comment by ghostreader86** [comment]
I'm still on 1.8.1 and everything runs fine.
Can you show us your items file?
You should define the rollershutter like this:

Rollershutter	UG_Treppenhaus_Rollladen		"Rollladen Treppenhaus UG [%d %%]"		<rollershutter>	(g_UG_Treppenhaus_Rollladen)

**Comment by cdjackson** [comment]
@ghostreader86 thanks - can you provide your item definition please?

**Comment by shrikantlahase** [comment]
My items defination is:

I tried 2 different definations:

Dimmer ROLLER_SHUTTER_162_163_43_1
{zwave="43:0:command=FIBARO_FGRM_222,type=shutter,restore_last_value=true"}
Dimmer ROLLER_SHUTTER_162_163_43_1
{zwave="43:0:command=SWITCH_MULTILEVEL,restore_last_value=true"}

**Comment by cdjackson** [comment]
What version of the ZWave binding are you using? I assumed (maybe incorrectly) that you were using OH2 since this is the HABmin2 project. Can you please confirm as it looks from your binding strings that it’s OH1 but please confirm.

**Comment by ghostreader86** [comment]
Thats the issue, define it as rollershutter to control it with up, down and
stop and%

Am 25.06.2016 07:13 schrieb "shrikant lahase" <notifications@github.com>:

**Comment by shrikantlahase** [comment]
Hi,
I have fgrm222 rollershutter , i want to  control it using values like 10,20,......etc. i don't want to use UP DOWN, STOP. 
I want scroll like functionality. 
I tried using SWITCH_MULTILEVEL command class but not working.

How to achieve this...?

Thanks,
Shrikant

**Comment by cdjackson** [comment]
You should be able to use a dimmer n your sitemap.

**Comment by shrikantlahase** [comment]
i am not getting your answer.
Are you saying like use of dimmer controller instead of rollershutter
controller...?

**Comment by cdjackson** [comment]
yes

**Comment by shrikantlahase** [comment]
electrically , we can not do wiring of rollershutter motor with dimmer
controller.....

**Comment by cdjackson** [comment]
I am not talking electrically - I said to use the dimmer in your sitemap.

**Comment by shrikantlahase** [comment]
ok.....chris

**Comment by shrikantlahase** [comment]
i will try ..... this.

**Comment by ghostreader86** [comment]
need to do the initialisation to be able to set a percent value...
Rollershutter item is able to accept up,down stop and percent values

Am 07.07.2016 10:45 schrieb "shrikant lahase" <notifications@github.com>:

**Comment by cdjackson** [comment]
What do you mean?

**Comment by ghostreader86** [comment]
Sorry, I mean you need to perform the calibration process before the fibaro rollershutter accepts % values. Otherwise it did not now, what 90% means, so it has to learn the endpositions first. Afterwards you can use sendcommand(name, up), down, stop or 90% for example

**Comment by cdjackson** [comment]
Ah - ok, thanks for the clarification.

**Comment by shrikantlahase** [comment]
its working after calibration
