### ISSUE TITLE
ZWave binding not showing...

### ISSUE THREAD

**Issue by feens** [cdjackson/HABmin2#117]
I managed to get OH2/HABmin2 up and running on my Mac finally, and I have the ZWave controller working (according to the logs and the node xml files its creating), but HABmin2 is showing that there are no bindings installed.  I'm using a nightly of OH2 an the ZWave 1.9 snapshot binding (as apparently switching to karat broke the older one).

Any thoughts?  Is there any way I can debug?

**Comment by petrklus** [comment]
@feens how did you get this to work? I am struggling to get the basic zwave functionality working in OH2

**Comment by cdjackson** [comment]
Please take a look on the forum -:

https://community.openhab.org/t/testing-z-wave-binding-on-openhab-2/7522

Any questions, then please ask there as lots of people are now using the OH2 ZWave binding.

Just one other point to note - the binding in the HABmin2 master branch is for OH1 ZWave binding. For using OH2, you need to use the one in the 'theme' branch. I will merge these in the next week.
