### ISSUE TITLE
OH2 - Snapshot - non-accessible method

### ISSUE THREAD

**Issue by chiflyer** [cdjackson/HABmin2#118]
After installing the new snapshot today of OH2, I added the habmin2 snapshot into the addons directory.  I used paperUI to install zwave 1.9.  

Now I received this error:

18:21:18.856 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 1: Node found
18:21:18.856 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller using Controller API
18:21:18.857 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller is Primary Controller
18:21:18.857 [INFO ] [age.SerialApiGetInitDataMessageClass] - ------------Number of Nodes Found Registered to ZWave Controller------------
18:21:18.857 [INFO ] [age.SerialApiGetInitDataMessageClass] - # Nodes = 1
18:21:18.857 [INFO ] [age.SerialApiGetInitDataMessageClass] - ----------------------------------------------------------------------------
18:21:19.380 [INFO ] [ding.astro.handler.AstroThingHandler] - Scheduled astro DailyJob at midnight for thing astro:sun:home
18:21:19.383 [INFO ] [ding.astro.handler.AstroThingHandler] - Scheduled astro PositionalJob with interval of 60 seconds for thing astro:sun:home
18:21:19.415 [INFO ] [marthome.event.ItemStateChangedEvent] - Sun_Elevation changed from NULL to -54.98
18:21:24.604 [INFO ] [ui.habmin.internal.servlet.HABminApp] - Stopped HABmin servlet
18:21:24.617 [ERROR] [org.openhab.ui.habmin               ] - [org.openhab.binding.zwave.configuration(19)] doFindMethod: Suitable but non-accessible method found in class org.openhab.ui.habmin.internal.services.zwave.ZWaveConfigResource
18:21:24.618 [ERROR] [org.openhab.ui.habmin               ] - [org.openhab.binding.zwave.configuration(19)] findMethod: Suitable but non-accessible method removeConfigurationService found in class org.openhab.ui.habmin.internal.services.zwave.ZWaveConfigResource, subclass of org.openhab.ui.habmin.internal.services.zwave.ZWaveConfigResource
18:21:24.618 [ERROR] [org.openhab.ui.habmin               ] - [org.openhab.binding.zwave.configuration(19)] unbind method [removeConfigurationService] not found; Component will fail
18:21:24.618 [ERROR] [org.openhab.ui.habmin               ] - [org.openhab.binding.zwave.configuration(19)] unbind method [removeConfigurationService] not found
18:21:24.976 [INFO ] [ui.habmin.internal.servlet.HABminApp] - Started HABmin servlet at /habmin
18:21:24.986 [ERROR] [org.openhab.ui.habmin               ] - [org.openhab.binding.zwave.configuration(200)] doFindMethod: Suitable but non-accessible method found in class org.openhab.ui.habmin.internal.services.zwave.ZWaveConfigResource
18:21:24.987 [ERROR] [org.openhab.ui.habmin               ] - [org.openhab.binding.zwave.configuration(200)] findMethod: Suitable but non-accessible method addConfigurationService found in class org.openhab.ui.habmin.internal.services.zwave.ZWaveConfigResource, subclass of org.openhab.ui.habmin.internal.services.zwave.ZWaveConfigResource
18:21:24.987 [ERROR] [org.openhab.ui.habmin               ] - [org.openhab.binding.zwave.configuration(200)] bind method [addConfigurationService] not found; Component will fail
18:21:24.987 [ERROR] [org.openhab.ui.habmin               ] - [org.openhab.binding.zwave.configuration(200)] bind method [addConfigurationService] not found

**Comment by hlat** [comment]
Hey Chris!
Not sure if it is totally related. Did the same - added last habmin2 snapshot in addons folder and added zwave binding via paper ui. Zwave Network works, but when I try to click in Habmin under configurations on "Zwave" I receive "Netzwerkfehler beim Laden der Zwave Geräteliste" and no nodes are shown.

Regards,
Herbert

**Comment by chiflyer** [comment]
What you describe is what I see as well.  That being said, I also get warning messages that Habmin2 cannot communicate with the Zwave device when performing reset commands to the device, etc.  I am using a Aeon Gen5.  As you can see the device connects, I am assuming the error "Suitable but non-accessible method found in class" is partly the problem.

**Comment by fuzzysb** [comment]
same problem here, i was working ok but i had OpenHab 1&2 installed, i blew away my build to rebuild only with OH2 and tidy it up, but now i cannot get this working because of the same issues. I have tried with multiple versions, but i am on todays build of OH2 & Habmin2,

2016-01-27 11:18:50.588 [ERROR] [org.openhab.ui.habmin               ] - [org.openhab.binding.zwave.configuration(9)] bind method [addConfigurationService] not found; Component will fail

**Comment by jrcourtois** [comment]
I got the issue on my side too.

**Comment by cdjackson** [comment]
Currently I don't plan to fix this - the plan is instead to get the OH2 ZWave binding released, and then to provide an updated HABmin.

The rational behind this is that the current master branch hasn't been worked on for a few months, with the exception of a few bug fixes. This version is only applicable for the OH1 ZWave binding, and the new branch will be merged once the OH2 ZWave is merged. I don't want to spend a lot of time trying to fix the old version when it will be outdated almost immediately - I prefer to spend the time getting the new ZWave binding working.

If all goes well, I hope to have the OH2 ZWave binding released for general test in the next few days. If we find an issue that changes this, I'll revisit the need to fix the existing binding (but I hope this won't be needed).

**Comment by jrcourtois** [comment]
OK, thanks for the answer.

**Comment by cdjackson** [comment]
The thing that will be needed for the OH2 binding before people can use it themselves is to update the database so that it supports your devices. Assuming the device is already included in the OH1 database, then you should be able to upload the xml file from OH1 into the database to generate the appropriate data -:

http://www.cd-jackson.com/index.php/zwave/zwave-device-database

Stay tuned :)

**Comment by luxus** [comment]
any updates on this? 
i check the database and im happy to see that my thermostat is already in it :dancer: 
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/183?layout=openhab2

is there any way to help? i already setup my devices via z-way

**Comment by cdjackson** [comment]
The OH2 binding is running. If you have issues please discuss on the forum.
