### ISSUE TITLE
Unable to load bindings, items, ect only loads sitemap

### ISSUE THREAD

**Issue by captain118** [cdjackson/HABmin2#12]
When I access the system it loads properly however it will only show my sitemap.  Everything else continuously tries to load and doesn't.

**Comment by cdjackson** [comment]
Do you have the JARs installed (both of them?).

**Comment by captain118** [comment]
Yes:

-rw-r--r-- 1 openhab openhab   32445 Feb  1 04:49
*org.openhab.binding.zwave-1.7.0-SNAPSHOT.jar*

-rw-r--r-- 1 openhab openhab 1127291 Feb  1 04:48
*org.openhab.io.habmin-1.7.0-SNAPSHOT.jar*

**Comment by cdjackson** [comment]
This doesn't look right - I don't think they have downloaded correctly. The zwave JAR is about 1MB, and in your list it's 32k.

**Comment by captain118** [comment]
I updated it and restarted with similar results.  Sitemap loads but nothing
else.  Is habmin2 only compatible with openhab2?

-rw-r----- 1 openhab openhab 1023371 Feb  1 18:41
org.openhab.binding.zwave-1.7.0-SNAPSHOT.jar

-rw-r----- 1 openhab openhab 1127291 Feb  1 18:41
org.openhab.io.habmin-1.7.0-SNAPSHOT.jar

**Comment by cdjackson** [comment]
No, its only compativle with openhab1.

Are there entries in the logs saying habmin is starting? Any errors in the logs?


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Kirk <notifications@github.com> </div><div>Date:02/02/2015  00:55  (GMT+00:00) </div><div>To: cdjackson/HABmin2 <HABmin2@noreply.github.com> </div><div>Cc: Chris Jackson <chris@cd-jackson.com> </div><div>Subject: Re: [HABmin2] Unable to load bindings, items, ect only loads sitemap
  (#12) </div><div>
</div>I updated it and restarted with similar results. Sitemap loads but nothing 
else. Is habmin2 only compatible with openhab2? 

-rw-r----- 1 openhab openhab 1023371 Feb 1 18:41 
org.openhab.binding.zwave-1.7.0-SNAPSHOT.jar 

-rw-r----- 1 openhab openhab 1127291 Feb 1 18:41 
org.openhab.io.habmin-1.7.0-SNAPSHOT.jar

**Comment by captain118** [comment]
I grep-ed openhab.log for zwave and habmin this was the only entry:

13:34:38.664 INFO  o.o.i.habmin.HABminApplication[:181]- Started HABmin
REST API at /services/habmin

**Comment by cdjackson** [comment]
What happens if you type the following into a browser -: [your openhab server:port]/services/habmin/persistence/items

It might also be worth installing HABmin1 if ou haven't already. I don't think this would cause the problem you're having, but there are some dependancies at the moment between the two (there are some XML files that describe the binding configuration that are installed with HABmin1 - it's not nice, but it's how it is at the moment).

It would also be interesting to see if HABmin 1 works in general as that would also help to narrow down the issue.

**Comment by captain118** [comment]
I get this from the URL:

<persistence>
<items>
<name>Light_GF_Kitchen</name>
<type>SwitchItem</type>
<icon>switch</icon>
<label>Kitchen Light</label>
<groups>GF_Kitchen</groups>
<services>logging</services>
</items>
<items>
<name>Light_GF_MBR_RightNightStand</name>
<type>DimmerItem</type>
<icon>switch</icon>
<label>Lamp</label>
<groups>GF_MasterBR</groups>
<services>logging</services>
</items>
</persistence>

Habmin1 loads:
Items and groups
Sitemaps
Bindings
Persistence
Rule Models (Which are my rules)
Bundles

Habmin1 does not load:
Translation Rules
Rules
Rules Library (Though I dont know that I have any)
Notifcations
Log Viewer

**Comment by cdjackson** [comment]
> 
> I get this from the URL: 
This looks fine, and given the next comment, I think things are probably running...


> 
> 
> Habmin1 loads: 
> Items and groups 
> Sitemaps 
> Bindings 
> Persistence 
> Rule Models (Which are my rules) 
> Bundles 
Good...

> 
> Habmin1 does not load: 
> Translation Rules 
> Rules 
> Rules Library (Though I dont know that I have any) 
> Notifcations 
> Log Viewer 
Ok - maybe there’s an issue with expectations :)  Of the above list, only rules should work - BUT - only if you create some… The Translation rules isn’t implemented as openhab started in a different direction - likewise translation rules.  The rule model display will show you the rules, but the “Rules” list will only show you rules that you’ve generated using the rule designer - i.e. from this screen you need to press the “ADD” button to create a rule - this isn’t the same as the rules model which is more the rules you will have manually created...

So, I would say that HABmin1 is working fine, and I think HABmin2 probably is as well if sitemaps are working. Rules is the same as HABmin 1 - you need to create a graphical rule and save it before it will show up in the window. If you go to the Charts menu, to create a chart you need to click the “Charts” button, and change this to “Items” to get the items list - here you can select items to graph, and then by clicking the cog button you should be able to save it, and it should then be listed as a chart…

Let me know if the above is working...=

**Comment by cdjackson** [comment]
Closing this issue as it's old. Any further problems, please open a new issue.
