### ISSUE TITLE
Add to Database MCO Touch Panel with 2 canals [ID:0x202/Type:0x4102]

### ISSUE THREAD

**Issue by Vorkosigan76** [cdjackson/HABmin2#124]
Hi, I would like to add my MCO Home Touch Panel with 2 canals to the HABmin database. (Im using Habmin1... not sure if this matters)

The node.xml generated is enclosed below
[node7.txt](https://github.com/cdjackson/HABmin2/files/120637/node7.txt)

The link to the XML in the product database is the following
http://www.pepper1.net/zwavedb/device/660/660-015f-4102-0202-05-03-43-01-00.xml

**Comment by cdjackson** [comment]
Can you please confirm the model number of your device?

**Comment by Vorkosigan76** [comment]
MCO Home MH-S412

**Comment by cdjackson** [comment]
Thanks- I can’t find a manual for this - just the 312. Do you know if it’s on the web somewhere?

**Comment by Vorkosigan76** [comment]
Yes I just added the link to my previous comment :)

**Comment by cdjackson** [comment]
Thanks - I’ll add that to OH1 later today - the entry in the database is here -:

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/272 <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/272>

**Comment by cdjackson** [comment]
All done - try tomorrows snapshot and let me know if it’s ok.

**Comment by Vorkosigan76** [comment]
Out of curiosity:
=> how do I try tomorrow's snapshot? WHat should I do?
=> And how can I check if its ok?

**Comment by cdjackson** [comment]
> On 7 Feb 2016, at 10:59, Vorkosigan76 <notifications@github.com> wrote:
> 
> Out of curiosity:
> => how do I try tomorrow's snapshot? WHat should I do?
> 
Go here (https://openhab.ci.cloudbees.com/job/openHAB1-Addons/ <https://openhab.ci.cloudbees.com/job/openHAB1-Addons/>) and download the ZIP. Grab the zwave binding and replace the existing binding in the /addons folder (i.e. make sure to remove the existing one).


> => And how can I check if its ok?
> 
HABmin should show the device name rather than a bunch of type/id numbers, and you should have associations you can set (although this should be done automatically).

**Comment by Vorkosigan76** [comment]
Hi, I have downloaded yesterday's snapshot with no effect. (I removed the old zwave binding and placed the new one in the folder)
Any idea why?

**Comment by cdjackson** [comment]
Yes - I suspect the error you’re getting now is different - unfortunately there was another bug (sorry) so please try again tomorrow…

**Comment by Vorkosigan76** [comment]
OK. Will do :)

**Comment by cdjackson** [comment]
Assuming this is ok - if not, please reopen.
