### ISSUE TITLE
Add to Database MCO Touch Panel with 1 canal [ID:0x201/Type:0x4102]

### ISSUE THREAD

**Issue by Vorkosigan76** [cdjackson/HABmin2#125]
HI @cdjackson , I have another device to add to the database

MCO Home MH-S411
Database http://www.pepper1.net/zwavedb/device/658
Manual https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjKmLXyovPKAhVCWRQKHZUoAGcQFggcMAA&url=https%3A%2F%2Fdoc.eedomus.com%2Ffiles%2FMH--S411-EU%2520UM.pdf&usg=AFQjCNEunUunpeozudbh0nl3T8giAHvMmw&sig2=R_qNxgKkIZe3XqefuuN8uA&bvm=bv.114195076,d.bGs
Node XML
[node17.txt](https://github.com/cdjackson/HABmin2/files/128810/node17.txt)

Thank you

**Comment by cdjackson** [comment]
That’s done -:

https://github.com/openhab/openhab/pull/4036 <https://github.com/openhab/openhab/pull/4036>

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/279 <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/279>

Please let me know if it’s all ok (or not!).

**Comment by cdjackson** [comment]
I assume this is ok so closing - if it's still got issues, please feel free to re-open...
