### ISSUE TITLE
latest habmin seems to put the old value instead of new value

### ISSUE THREAD

**Issue by marcelrv** [cdjackson/HABmin2#127]
Hi Chris,

with todays version of the habmin jar, looks like the config updates have an issue.,
It looks like you put the old value instead of the new value

**Comment by marcelrv** [comment]
![habmin](https://cloud.githubusercontent.com/assets/5871213/13198592/5fb75116-d80d-11e5-87e5-2cfe6fd44711.png)
screenie

**Comment by cdjackson** [comment]
Thanks - I’ll take a look. I refactored this code last night to fix a race condition while grabbing multiple data from different REST endpoints (since we added the channel-type endpoint…).

**Comment by cdjackson** [comment]
I don't seem to able to reproduce this... 

![image](https://cloud.githubusercontent.com/assets/1041475/13199554/bedf2516-d820-11e5-8c39-19bd0a67edd9.png)

**Comment by cdjackson** [comment]
Are you still seeing this? I certainly don't see it here and others are able to save data ok as we've been doing tests on the Zwave binding which involves changing a lot of parameters.

**Comment by marcelrv** [comment]
with your latest build indeed I don't see this anymore
