### ISSUE TITLE
Z-Wave Database: Fibaro FGSD002

### ISSUE THREAD

**Issue by fvdpol** [cdjackson/HABmin2#128]
Please have a look at the z-wave database entry for the Fibaro FGSD002.  
My device (EU version) is not being recognised by the OpenHAB2 zwave binding (version 2.0.0.201602230202) although a record for the device exists in the device database:

Found existing database entry for the FGSD002
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/129

Database shows incorrect Class definition:
   Generic Class	GARAGE_DOOR
   Specific Class	SIMPLE_GARAGE_DOOR

Expected:
   Generic Class	ALARM_SENSOR
   Specific Class	SMOKE_SENSOR_ROUTING or ALARM_SENSOR_ROUTING

Firmware version listed in database is from 3.1 to 3.1; seems my device is listed as version 3.3:

      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_SLAVE_ENHANCED</libraryType>
        <protocolVersion>4.5</protocolVersion>
        <applicationVersion>3.3</applicationVersion>
      </versionCommandClass>

full xml from userdata/zwave in attached zip file
[Fibaro_FGSD-002EU.zip](https://github.com/cdjackson/HABmin2/files/142740/Fibaro_FGSD-002EU.zip)

**Comment by cdjackson** [comment]
I’ve removed the version constraint which shouldn’t be required unless different versions have different configurations.

**Comment by fvdpol** [comment]
Thanks @cdjackson! I tested using latest OH2 nightly and the device is now detected correctly. 

The device class defined in the database still shows the Garage Door though, which is not correct, but is currently not causing any issue for my setup. Does this still need to be corrected before closing the issue or can we simply ignore this?

**Comment by cdjackson** [comment]
Don’t worry about the class type - you can’t change this easily. I need to think about how to do this without upsetting too much code so we can close this I think.

Thanks.
Chris
