### ISSUE TITLE
best way to add habmin2 when running from eclipse?

### ISSUE THREAD

**Issue by azim0ff** [cdjackson/HABmin2#130]
Hi, I am trying to use habmin2 binding in a development installation (running from eclipse). What is the best way to achieve this?

**Comment by cdjackson** [comment]
The easiest way, if you don't want to import the source is just to import the JAR (using File | import menu in Eclipse).

**Comment by azim0ff** [comment]
Which option should be chosen? General/File_System? If I do that, it wants to add it (jar file) to an already existing project.

**Comment by cdjackson** [comment]
Good question. I'd need to take a look later as I don't have Eclipse here.

**Comment by azim0ff** [comment]
Ok. Just out of curiosity - you don't use eclipse for developing?

**Comment by cdjackson** [comment]
Yes, I use Eclipse for Java development, but not Javascript/web development.

When I said 'I don't have Eclipse here', I just meant right this very minute as I'm not sitting in front of my development environment and am answering on my phone...

**Comment by cdjackson** [comment]
So I just tested this using the "Archive File" option, and then just selecting a folder (I think I chose infrustructure which just contains the configuration etc anyway).

**Comment by azim0ff** [comment]
Thank you for looking into this. I followed your method with a small modification. I created a dummy project - empty directory with a .project file, then imported this empty project into OH2 Add-ons. Into this new project, I Import/Archive_File the habmin .jar file. After enabling habmin bundle in the run config I am now able to use it from within eclipse. Thanks again!
