### ISSUE TITLE
Unable to start HABmin2 after installing jar in addons

### ISSUE THREAD

**Issue by shahronak** [cdjackson/HABmin2#131]
When I navigate to the HABMin URL, I get a 404 error:
HTTP ERROR 404

Problem accessing /habmin/index.html. Reason:

    Not Found

Powered by Jetty://

I copied the habmin .jar file in to my /opt/openhab/addons/ directory and restarted openhab. This still did not let me start the dashboard. 

Do you know how to fix this issue?

**Comment by cdjackson** [comment]
If you don't see the dashboard, then there's a problem with your OH2 installation.

If this is just a problem with HABmin, then the most common problem is that the file doesn't download correctly from Github. The file should be 4MB long - if it's only 30kB or something, then this is a problem.

**Comment by shahronak** [comment]
I can see the dashboard with 4 UI options but not HABmin. I noticed the file sizes were small and tried the raw download method. Testing it now.

**Comment by shahronak** [comment]
I got it working! Now I'm running in to a different issue where my ZWave controller stops working. Here are my logs: 

09:33:59.201 [ERROR] [org.eclipse.smarthome.core.transform] - [org.eclipse.smarthome.action.transformation.action(73)] Circular reference detected, getService returning null
09:34:13.475 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /ui
09:34:14.485 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start
09:34:15.982 [INFO ] [ulation.internal.HueEmulationServlet] - Started Hue Emulation service at /api
09:34:18.651 [ERROR] [o.myopenhab.internal.MyOpenHABClient] - Socket.IO error: not authorized
09:34:21.012 [INFO ] [ab.ui.cometvisu.servlet.CometVisuApp] - Started CometVisu UI at /cometvisu serving ../../../CometVisu/src/
09:34:21.166 [INFO ] [ng.zwave.internal.ZWaveActiveBinding] - Update config, port = /dev/ttyUSB0
09:34:21.171 [INFO ] [b.core.service.AbstractActiveService] - ZWave Refresh Service has been started
09:34:21.218 [INFO ] [ve.internal.protocol.ZWaveController] - Starting Z-Wave controller
09:34:21.221 [INFO ] [ve.internal.protocol.ZWaveController] - Z-Wave timeout is set to 5000ms. Soft reset is false.
09:34:21.225 [INFO ] [ve.internal.protocol.ZWaveController] - Connecting to serial port /dev/ttyUSB0
09:34:21.394 [INFO ] [ve.internal.protocol.ZWaveController] - Serial port is initialized
09:34:21.433 [INFO ] [ui.habmin.internal.servlet.HABminApp] - Started HABmin servlet at /habmin
09:34:21.576 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
09:34:21.636 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
09:34:22.396 [INFO ] [ve.internal.protocol.ZWaveController] - Disconnected from serial port
09:34:22.402 [INFO ] [ve.internal.protocol.ZWaveController] - Stopped Z-Wave controller
09:34:22.595 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'logging.persist'
09:34:23.028 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'rrd4j.persist'
09:34:26.184 [INFO ] [b.core.service.AbstractActiveService] - ZWave Refresh Service has been shut down

**Comment by cdjackson** [comment]
I'd suggest asking this question on the openhab forum, but also please provide a debug logfile.

**Comment by shahronak** [comment]
Will do :). Thanks!
