### ISSUE TITLE
An offline Thing cannot be remove in Habmin

### ISSUE THREAD

**Issue by xsnrg** [cdjackson/HABmin2#132]
If a thing is offline (Red X circle) it cannot be deleted through Habmin.  The delete button is not active.  It can be deleted successfully in paper UI.

**Comment by cdjackson** [comment]
I can't reproduce this - I'm able to select and delete an offline thing just fine. I tested this by removing the Z-Wave stick from my system and restarting OH2. The Z-Wave stick was offline, and I deleted it...

Is this thing you're trying to delete just offline, or is there no thing handler (normally meaning no binding) for the device. In this case, HABmin should show a delete button directly in the list - either way, it seems to work here...

**Comment by xsnrg** [comment]
The steps I went through were to take a device that was working, shut down OH2, remove the stick from the server, un-include the device, plug the stick back in, and then start openHAB.  The device still showed up in Habmin, but nothing would appear in the right pane when the node was clicked.  The node displayed a red X and could not be selected.

**Comment by cdjackson** [comment]
If you shut down the server then you really should refresh HABmin as it loses the connection to the event sources, and it doesn't grab all the data again since it works primarily off the event source to avoid too much polling (which caused problems in OH1 on slow devices!).

**Comment by cdjackson** [comment]
I've found an error that might be what you're seeing. If the device is not found in OH, then it can't be selected, and there's no error. I've added a warning for now - at least this will allow us to confirm the problem is what you see, and I can look further then.

**Comment by xsnrg** [comment]
That is true, I did not shut the browser down, but I did hard refresh the page.  In theory that should have loaded all the things the page needs to display correctly again.  I loaded PaperUI after this, and it also showed the thing as offline but the delete button was available.  It felt like a UI issue where the state the thing was in wasn't handled... and you just replied as I was typing.  That does sound like the problem.

**Comment by cdjackson** [comment]
Hard refresh should be fine… I’ll try and push an update later tonight so maybe you can confirm if it at least gives the error…

**Comment by cdjackson** [comment]
This should now be fixed as I'm handling failed responses better, so the thing should now be selectable, and therefore deletable...

**Comment by xsnrg** [comment]
Can remove now. Thank you
