### ISSUE TITLE
Safari pretty much non-functional

### ISSUE THREAD

**Issue by mishakim** [cdjackson/HABmin2#134]
After a day of working fine, HABmin in Safari is just not working at all. It loads, but for each of the categories on the left, only the top one is clickable. E.g., under Configuration, each of Bindings, Thing Config, Items, Floorpan turn white on mouseover, but only Bindings does anything when clicked. But what it does isn't much - the Bindings page loads, but I just have a spinning arrows and "loading..." under Installed Bindings.
Similarly, under Tools, Z-Wave log viewer is clickable but shows a blank page, Network Viewer does nothing at all when clicked.
None of the Sitemaps load anything - just blank white space.
Rules has the same loading...; Scheduler does open, but I'm not sure what it's supposed to do in the first place

everything works under Chrome.  Nothing showing up in the debug log, but I probably have that set wrong (I tried log:set DEBUG org.openhab.ui.habmin)
OS X 10.11.3, Safari 9.0.3, Habmin from 3/9

**Comment by mishakim** [comment]
of course now it's working -- I closed and restarted the browser, and that _didn't_ fix it, but closing just the browser _window_ did.

**Comment by cdjackson** [comment]
I guess this is some sort of caching problem. Given it's working ok after you restarted, I will close, but if there are further issues, please open an issue...
