### ISSUE TITLE
Action buttons that are not advanced don't show when 'show advanced settings' is selected

### ISSUE THREAD

**Issue by marcelrv** [cdjackson/HABmin2#137]
In my xml  I defined 2 action buttons, one advanced, the other not.
The one that is not advanced does not show when  'show advanced settings' is selected.
I would expect both buttons to show at that time

```
			<!-- Trigger reset action from habmin menu -->
			<parameter name="action-cubeReset" type="integer" groupName="actions">
				<label>Reset Cube Configuration</label>
				<description>Reset the MAX! Cube room and device information. Devices will need to be included again!</description>
				<default>-1</default>
				<advanced>true</advanced>
			</parameter>
			<!-- Trigger reboot action from habmin menu -->
			<parameter name="action-cubeReboot" type="integer" groupName="actions">
				<label>Restart Cube</label>
				<description>Restarts the Cube.</description>
				<default>-1</default>
				<advanced>false</advanced>
			</parameter>

```

**Comment by cdjackson** [comment]
Yes, both should be displayed in this case.

**Comment by cdjackson** [comment]
This should be fixed now - if you're using source. I'll compile up a new version tomorrow probably as have a few more things to finish first.

**Comment by marcelrv** [comment]
Super fast! Thanks
Np, my PR with this combination  isn't merged yet.
Op 14 mrt. 2016 00:11 schreef "Chris Jackson" <notifications@github.com>:
