### ISSUE TITLE
Option to add/edit Tags in Items

### ISSUE THREAD

**Issue by hfanieng** [cdjackson/HABmin2#139]
Due to missing the option to add/edit Tags to items in HABmin it's necessary to assign them in an item-file:

Switch 	zwave_device_b172f74e_node7_switch_binary1	"light Bar" [ "homekit:Lightbulb" ]

Would be ne nice to have an option in HABmin to assign the Tags :+1: 

![tagssss](https://cloud.githubusercontent.com/assets/3420120/13861088/c08587fa-ec8b-11e5-8f26-2e09500e4100.png)

Here i want to assign the [ "homekit:DimmableLightbulb" ]

**Comment by xsnrg** [comment]
This is related:

https://github.com/eclipse/smarthome/issues/1122

**Comment by hfanieng** [comment]
Thank you for this information.

**Comment by cdjackson** [comment]
This is now added in the latest release.

**Comment by trusk89** [comment]
@cdjackson sorry to bother, but where? In my case its still read only.

**Comment by lini500** [comment]
In my case too...
