### ISSUE TITLE
Link channel to an existing item don't work

### ISSUE THREAD

**Issue by hfanieng** [cdjackson/HABmin2#140]
![channel-linking-existing-item](https://cloud.githubusercontent.com/assets/3420120/13899470/4045e142-edef-11e5-88a4-353fc0bb285f.png)

**Comment by cdjackson** [comment]
Thanks, but can you explain why it doesn’t work? Is there an error? What happens exactly?

Thanks
Chris

**Comment by hfanieng** [comment]
Hi @cdjackson, 

the 1st error is see ist %%KEY_NOT_FOND%%, i can select 3_HomeKit_node7_switch_binary1 and click the save button but nothing happens. 

I hope to solve my problem with creating duplicate items if assign an existing item from a sitemap file as 2nd item via HABmin to a channel.

HABmin-Version ist 2.0.0.201603151333.

The %%KEY_NOT_FOND%% happens also if i want to create a new rule:
![key_not_found](https://cloud.githubusercontent.com/assets/3420120/13899553/6e73fe9e-edf1-11e5-8d7c-596b4a2a9e23.png)

Cheers
Heiko

**Comment by cdjackson** [comment]
The key not found is just a definition - I’ll fix that…  I recently changed all the translation strings to make it easier to translate using the online tool, and some haven’t converted properly…

Ok - I’ll take a look at the reported problem with saving links. At the moment I’ve not got a development environment working on my main machine as an update this morning seems to have killed everything here :( Once that’s sorted I’ll take a look.

**Comment by cdjackson** [comment]
This should be fixed in the next release.
