### ISSUE TITLE
Trouble installing Habmin

### ISSUE THREAD

**Issue by rndmsfree** [cdjackson/HABmin2#143]
This is probably a total noob question, but I've having problems seeing Habmin in my browser.  I downloaded the latest Habimn2 release .jar and moved it to /opt/Openhab2/addons.  I verified the file moved properly, rebooted just because I didn't know if I needed to, and then launched openHab2.  When I tried going to the normal dashboard selection screen, Habmin isn't available to choose.  Also tried to go to there manually with http://192.168.0.xx:8080/habmin/index.html and it says the file is not found.  Any suggestions?  I'm sure it's something simple

**Comment by intrepidsilence** [comment]
I am having this same issue.  I am using the latest output from the working directory and this is what I am seeing when running a bundle:diag from the openhab prompt:

openhab> bundle:diag
HABmin User Interface (174)
---------------------------
Status: Installed
Unsatisfied Requirements:
osgi.wiring.bundle; filter:="(osgi.wiring.bundle=javax.servlet)"

Pretty sure that is why this is not working and all of my searches say that this should have been fixed back in January so maybe this was a regression?

These are the bundles I installed in addons:

org.openhab.ui.habmin_2.0.0.SNAPSHOT-0.1.2.jar
org.openhab.binding.zwave_2.0.0.201603162056.jar

**Comment by cdjackson** [comment]
Strange - the java.servlet package is not a dependancy -:
 javax.servlet.http,
 javax.ws.rs,
 javax.ws.rs.core,
 org.apache.commons.io,
 org.eclipse.emf.common.util,
 org.eclipse.emf.ecore,
 org.eclipse.smarthome.config.core,
 org.eclipse.smarthome.core.items,
 org.eclipse.smarthome.core.library.types,
 org.eclipse.smarthome.core.persistence,
 org.eclipse.smarthome.core.types,
 org.eclipse.smarthome.io.rest,
 org.eclipse.smarthome.model.core,
 org.eclipse.smarthome.model.items,
 org.eclipse.smarthome.model.sitemap,
 org.eclipse.smarthome.ui.items,
 org.openhab.ui.dashboard,
 org.osgi.service.component,
 org.osgi.service.http,
 org.slf4j

What version of OH2 are you using?

**Comment by rndmsfree** [comment]
I'm using the Openhab2 2.0.0 offline distro and just downloaded Habmin 0.0.15 from the releases folder today.

**Comment by rndmsfree** [comment]
Ok - my zwave binding is the 1.8.2 version.  I suppose I should go find the 2 version.  I'm so new at this and lost, but I understood that the Openhab 1.x bindings would mostly work with v2.

**Comment by cdjackson** [comment]
Yes - but what version of openhab2 - when was it released?

HABmin2 version 0.0.15 will likely not work - it’s far too old. You should use the most recent version from the addons folder.

**Comment by cdjackson** [comment]
The version of the zwave binding is another issue that’s not related to HABmin, but you are using a very old version of HABmin so you should upgrade to the latest snapshot.

**Comment by rndmsfree** [comment]
I am not sure about the openhab version - I got the one from the openhab.org downloads page.  the 2.0.0 offline snapshot.  Sorry that's not helpful.  Total beginner just trying to tread water here.

I didn't realize this version of Habmin was so old - I took it from the release folder.  I will dig up a more recent one and try again.

**Comment by rndmsfree** [comment]
Do you recommend using these instead?

https://github.com/cdjackson/HABmin2/tree/master/output

**Comment by cdjackson** [comment]
I would use a recent snapshot of OH2 - from here (https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ <https://openhab.ci.cloudbees.com/job/openHAB-Distribution/>), and the most recent snapshot of HABmin from here (https://github.com/cdjackson/HABmin2/raw/master/output/org.openhab.ui.habmin_2.0.0.SNAPSHOT-0.1.2.jar).

The current release of HABmin is very old and you are right, I should properly release a new version - a lot has changed in the last few weeks...

**Comment by rndmsfree** [comment]
Thank you!  I will do both and report back.

**Comment by intrepidsilence** [comment]
cdjackson:  I made sure that I have installed the offline version of openHAB that you pointed to above and the HABmin version you pointed to and the Z-Wave bundle in the same location as the HABmin you pointed to.  Now I don't have any odd missing dependencies but I still cannot get to habmin.  404 when I got to http://<MYIP>:8080/habmin/index.html as the docs suggest.  Nothing on the front page where the docs say there should be a link.  bundle:diag is clean.  HABmin bundle shows an installed state in bundle:list.  Where can I look to see what is going on?

**Comment by rndmsfree** [comment]
Well, I dumped my entire Openhab2 directory, downloaded the things you posted and now HABmin is loading for me.  It freezes up from time to time, but that may be because it's choking on the fact that I haven't added any devices yet.  Thanks for the links to the files!

**Comment by intrepidsilence** [comment]
Ok, I just realized that you are supposed to rename the file to take out the version info.  You really need to have some instructions or have a release version of what is current.  Way too confusing for starters.

**Comment by cdjackson** [comment]
You don’t need to rename the files in OH - filenames don’t matter at all…

**Comment by intrepidsilence** [comment]
Well, I got an error in the log that said it could not resolve the habmin bundle.  I renamed it and the error went away and I saw the HABmin interface for the first time in hours of tinkering with this.  I hear you that file names are not supposed to matter but for some reason in my case they did.  It as the only thing I changed before it worked.

**Comment by cdjackson** [comment]
No idea then, but I’m sure it’s not the name.
