### ISSUE TITLE
Add to Database Danfoss Living Connect [ID:2/Type:8005]

### ISSUE THREAD

**Issue by Vorkosigan76** [cdjackson/HABmin2#144]
Hi, I have thermostat at home which are

Danfoss Living Connect SW 4.2
http://www.pepper1.net/zwavedb/device/6/6-0002-8005-0001-06-02-43-02-06.xml

The associated node is the following

[node6.txt](https://github.com/cdjackson/HABmin2/files/190432/node6.txt)

**Comment by cdjackson** [comment]
Can you provide the model number, and preferably a link to the manual PDF.

**Comment by Vorkosigan76** [comment]
When I purchased it, there was no such thing as a model number, but inside mine is written SW 4.2

The manuals are below
http://heating.danfoss.com/PCMPDF/living-connect_OEM_VQIDA15T_013R9563.pdf
http://heating.danfoss.com/PCMPDF/living-connect_VIIDH102.pdf

**Comment by cdjackson** [comment]
Thanks. Does 4.2 make it quite new? (just trying to understand the products).

**Comment by Vorkosigan76** [comment]
I would say it's rather new as I bought these less than 1 year ago from Danfoss.

**Comment by Vorkosigan76** [comment]
Everything is ok or do you need more information?

**Comment by cdjackson** [comment]
It’s ok. The files you sent have a date of a few years ago, and given there’s no information to say that this is any different to the other devices already in the database, I will just link it to an existing device. If you later find that there’s something missing, we can create a separate device for this version and update it accordingly.

**Comment by Vorkosigan76** [comment]
OK, great :) My documentation seems pretty similar if not identical to the one i provided you.

When will you binding be updated by the way?

**Comment by cdjackson** [comment]
> When will you binding be updated by the way?
> 
Good question - it might still be another few days. I need a few things merged upstream in ESH first - some was done this morning, but there’s one major thing I’m waiting for...

**Comment by cdjackson** [comment]
Is this now included? Can we close?

**Comment by Vorkosigan76** [comment]
I just updated the zwave.jar... But it still displayed as Danfoss [ID:2, Type: 8005]

So cannot close. Any idea why?

**Comment by cdjackson** [comment]
Nope - no idea. The codes are in the database, so not sure what else to do. Can you provide the XML so I can double check everything?

**Comment by cdjackson** [comment]
Closing. If this is still an issue, then please provide further information.
