### ISSUE TITLE
Add to database Leviton DZPD3 Lamp Module [ID:2 / Type:334]

### ISSUE THREAD

**Issue by n0ki** [cdjackson/HABmin2#146]
I have this dimmable lamp module that needs to be added to database.

http://products.z-wavealliance.org/products/1020

http://www.leviton.com/OA_HTML/ibcGetAttachment.jsp?cItemId=2KMCfyepUWFwPgjoaIRN7Q&label=IBE&appName=IBE&LEVCOMP_pses=ZG9A35CE7C9FCBE67E0972DF13C01E29069273E82A703B4405C7F3DC7BDFCE8AF933FAE9AEF9B455D2CBDDEDC7229BDA1BAB0725217D972009&minisite=10251

Attached node file:
[node2.txt](https://github.com/cdjackson/HABmin2/files/191299/node2.txt)

**Comment by cdjackson** [comment]
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/322 <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/322>

Is this for OH1 or OH2?

**Comment by n0ki** [comment]
OH2, working fine in OH1

**Comment by cdjackson** [comment]
Ok - thanks. It will get through into OH2 in the next update (might not be tonight though).

**Comment by n0ki** [comment]
Thanks!

**Comment by cdjackson** [comment]
Can we close this?

**Comment by n0ki** [comment]
I still can't get it to work in OH2, OH1 is fine though, need to dig in more. But yes , this database issue can be closed and must not have been the issue!
