### ISSUE TITLE
The dashboard is not well displayed

### ISSUE THREAD

**Issue by npapadimitriou** [cdjackson/HABmin2#149]
Hi
I am using OH1.8.2 and habmin2-0.1.2 and I am having  this 
![dash](https://cloud.githubusercontent.com/assets/13378588/14158462/d61e6ada-f6d8-11e5-9318-96cb398d2b46.PNG)
Is habmin22-0.1.2 incompatible with OH1.8.2 and if yes, which  habmin version should I use?? Have I done something wrong in the installation because it is  a little bit fuzzy ?Is there any easy install tutorial you know for noobies
Thank you in advance

**Comment by cdjackson** [comment]
The latest versions of HABmin are only supported in OH2 - sorry.

**Comment by npapadimitriou** [comment]
Could you please inform me up to  which version could I use?Thanx

**Comment by cdjackson** [comment]
You can use it with openHAB-2 latest version - not openHAB-1.
