### ISSUE TITLE
Last release lacks APK file

### ISSUE THREAD

**Issue by IzzySoft** [cdjackson/HABmin2#151]
Hiya,

the latest release somehow misses the `.apk`. Would you consider attaching that in the `releases/` section as well? For [some background](https://android.izzysoft.de/repo), my repo-updater could fetch it from there automatically. That is, provided the `Manifest` identifies it with the correct version as well – the last one (`HABmin2-0.0.15.apk`) presented itself as "1.0.0":

    package: name='com.cd_jackson.habmin' versionCode='10000' versionName='1.0.0'

Thanks in advance!

**Comment by IzzySoft** [comment]
Um … any chances, or not? Or just undecided? ;)

**Comment by cdjackson** [comment]
Not undecided - just not had the chance to look at this. When I merged the versions back in January I found that it no longer compiled, and I’ve not had the chance to look at it yet - sorry - there’s a lot happening…

**Comment by IzzySoft** [comment]
Thanks for the feedback! No pressure then. I just wasn't sure if the issue was noticed at all. Considering it's no longer compiling currently, there's nothing you can do *now* – so if you say as soon as the next release is due, and does compile, you'll attach the `.apk` again, I'll be patient and look forward to that :smiley_cat:

**Comment by cdjackson** [comment]
It’s the cordova part that’s not compiling. It looks like the compiler changed. So the main HABmin source is ok, but the integration with Cordova is the issue, and this is what produces the APK. I’ll try and find a few minutes some time to look at this since I do want to restore this feature...

**Comment by IzzySoft** [comment]
Any luck so far? Not pressing (you take your time when you can), just asking :)

**Comment by cdjackson** [comment]
Sorry - no, I've not had a chance to look at this. Cordova has gone through a few updates - I think I was using version 3, and it's now on version 6. I'll try and find a few minutes over the next day or so to see if it's simple to upgrade (I would hope and expect so, but let's see)...

**Comment by IzzySoft** [comment]
I keep my fingers crossed it will be just a simple update to get it working again. Looking forward to the `.apk` – whenever it is ready. I might ping you again in a couple of weeks if I hear no news, if that's OK for you (just giving a reminder ;)

**Comment by cdjackson** [comment]
I have an APK generated - just waiting for my old Note2 to charge to see if it works...

**Comment by cdjackson** [comment]
It works…

I need to work on it a bit to make it properly usable again, but it does run at least. Give me a few days to sort this out - and yes, you can hassle me if you don’t hear from me in a few days :)

**Comment by cdjackson** [comment]
please email me directly - chris -at- cd-jackson.com and I'll send you an APK to try - my old Note2 is playing up! :(

I've also updated the build to automatically increment the versionCode and sync the versionName.

**Comment by cdjackson** [comment]
This is now included in the release again.

Any problems, please open separate issues.

**Comment by IzzySoft** [comment]
Thanks a lot! But is it intended that each `.apk` claims to be version 1.0.0 instead of reflecting the real version? Causes conflicts when multiple versions reach the repo, so no auto-update possible. Just asking :)

**Comment by cdjackson** [comment]
I’ll update this - it should be linked automatically - I recently added a script to update the androidVersionCode automatically which was the latest issue, but the version in theory should have been linked already. Can you open a separate issue.
