### ISSUE TITLE
Feature request: On demand device heal

### ISSUE THREAD

**Issue by xsnrg** [cdjackson/HABmin2#155]
In older versions of Habmin, before zwave2, there was the option at the device level to heal the device.  If this is possible with the new 2.0 binding, it would be handy to have when people move devices around.  The ability to heal the network on demand is also desired.

The use case is my own network and the rate at which I move things around.  I would use these functions to try to get rid of some timeouts, forcing devices to find good neighbors in the mesh.

**Comment by cdjackson** [comment]
The current binding does not support heal at all. I’m yet to decide if this is really useful - in theory the actual re-routing etc is all done by the stick - the binding can’t influence it...

**Comment by xsnrg** [comment]
So even the current scheduled heal in the controller config is a placebo?

![heal](https://cloud.githubusercontent.com/assets/1186921/14322661/46933a34-fbe3-11e5-8314-1ebd8f3dca2c.png)

**Comment by cdjackson** [comment]
Correct. As said earlier, I’m yet to decide if heal really helps or if it’s a hindrance. It doesn’t do anything to help routing at the protocol layers since the stick is meant to do that itself.
