### ISSUE TITLE
habmin2 with OH1.8.2 HTTP ERROR 403 - Forbidden

### ISSUE THREAD

**Issue by martinmatias** [cdjackson/HABmin2#156]
Hi, I'm running OH1.8.2 and trying to use habmin2 but I'm getting a forbidden error.
I think I'm followed correctly the instruction. Can you please help me identifying the error?. I'm running OH1.8.2 as root Bellow are the folder installation of admin components:
```
cubie@Cubian:/opt/openhab/webapps$ ls
0.1.3.tar.gz  habmin2  images  README  static
cubie@Cubian:/opt/openhab/webapps$

```
```
cubie@Cubian:/opt/openhab/webapps/habmin2$ ls
bower.json       CONTRIBUTING.md  module.prefix  package.json
build.config.js  cordova          module.suffix  README.md
CHANGELOG.md     Gruntfile.js     openhab2       src
changelog.tpl    karma            output         vendor

```
```
cubie@Cubian:/opt/openhab/addons$ ls
org.openhab.binding.mqtt-1.8.2.jar
org.openhab.binding.zwave-1.8.0-SNAPSHOT.jar
org.openhab.persistence.rrd4j-1.8.2.jar
org.openhab.ui.habmin_2.0.0.SNAPSHOT-0.1.3.jar
README
```
Hope you can help me
Kind Regards
Martin

**Comment by cdjackson** [comment]
HABmin2 is not compatible with openHAB 1.8.2.

**Comment by martinmatias** [comment]
Ok, understood.Witch is the latest version of OH1 that supports habmin2? I think I'm not ready to move to OH2 since still in beta. (and not so many examples as OH1)
I understand that you are developing over habmin2 rather than habmin1 and I want to use the latest one.
Regards
Martin

**Comment by cdjackson** [comment]
No version of OH1 works with HABmin2 - HABmin2 is designed to work with OH2.

**Comment by Live1orDie1** [comment]
The wiki lists instructions for installing HABmin2 on OH1. So if it is the case that no version of OH1 works with HABmin2, or that no issues should be brought up about it, the instructions should probably be removed/revised.

https://github.com/cdjackson/HABmin2/wiki/OpenHAB-1-installation

**Comment by cdjackson** [comment]
Thanks - I'll remove this section as it's outdated now and I clearly missed it when I updated the main pages..
