### ISSUE TITLE
Cooper RF9540-N & RF9542-Z showing up as unknown device

### ISSUE THREAD

**Issue by rgerrans** [cdjackson/HABmin2#160]
I'm just starting to make the transition over to OpenHab.  I tried adding one of my Cooper dimmers (and aux dimmer) through the HABmin2 interface but they show up unknown devices.  I saw in the device database that both are listed as needing more information.  So I'm assuming they aren't usable with OpenHab presently?  Is there any information I can pull from them (I was reading about uploading the node xml file) that would help get them working?

**Comment by xsnrg** [comment]
Greetings and welcome to openHAB.  I just looked at the 9540, and you are correct, it is missing the XML file, as is the 9542.  If you would like, you can register on the database site to upload your own XML files, or attach them here and somebody will upload them for you.  If you do register, send @cdjackson  a note so he can enable your account.

**Comment by rgerrans** [comment]
Thanks xsnrg. 

 Attached is the RF9540-N xml file.  I'll have to reconnect the 9542 later and copy that file too.
[Cooper RF9540-N.zip](https://github.com/cdjackson/HABmin2/files/232765/Cooper.RF9540-N.zip)

I'll see about getting an account for upload from @cdjackson later.

**Comment by xsnrg** [comment]
XML uploaded.  Database entry published.  It should be in tomorrow's build after @cdjackson  does the commit.  Feel free to upload any others you may have.

**Comment by rgerrans** [comment]
Thanks.  I see that the 9540 is now showing good in the device list and just tried the 0423 zwave build but still had the same issue of device unknown?

Also, here is the xml for the 9542.
[RF9542-Z.zip](https://github.com/cdjackson/HABmin2/files/232981/RF9542-Z.zip)

**Comment by cdjackson** [comment]
Thanks - I’ve loaded the XML and updated the database. Please see how it looks in the binding tomorrow...

**Comment by rgerrans** [comment]
Thanks @cdjackson .  I'll test it tomorrow and let you know if I see any issues.  I'll request an account as well to do direct uploads going forward

**Comment by xsnrg** [comment]
Note that the process is to first get the entry into the database, it then needs to be exported to be picked up in a PR and commit to master.  After the commit, master has to have a clean build for it to show up in the binding.  I had missed the commit time window to get your device in last night.  Both should now be in tonight's build.

**Comment by cdjackson** [comment]
> On 23 Apr 2016, at 20:48, Jim <notifications@github.com> wrote:
> 
> Both should now be in tonight's build.


That’s assuming I create a version tonight - there are a lot of changes made to the binding today and testing is still ongoing… It will probably be ok, but don’t shoot me if it’s not :)

**Comment by xsnrg** [comment]
> That’s assuming I create a version tonight

Well there is always that :)  Hardly a fire-able offence.

**Comment by rgerrans** [comment]
> Well there is always that :) Hardly a fire-able offence.

Agree.  

I have to fix an issue with my Vera config but after I have that resolved I do another try with the latest.  Thanks again!!

**Comment by cdjackson** [comment]
It’s merged now…

**Comment by rgerrans** [comment]
@cdjackson Was it merged in this morning's build or will be in tomorrow's?  If it was in todays, no luck getting them recognized.  Thanks.

**Comment by xsnrg** [comment]
The build should kick off in a little more than an hour from now.

**Comment by rgerrans** [comment]
Thanks @xsnrg

**Comment by rgerrans** [comment]
Just grabbed the 0425 build and still doesn't recognize the 9540 or the  9542.  Are there any files / logs I can pull to help troubleshoot?

**Comment by rgerrans** [comment]
Nevermind, user error.  The old zwave binding was still active.  Uninstalled it and now both installed correctly!!!

**Comment by rgerrans** [comment]
We are good to go (after user error of not getting the old zwave binding uninstalled).  Thanks for all the help!!
