### ISSUE TITLE
Rule created with HABmin uses postUpdate instead of sendCommand

### ISSUE THREAD

**Issue by denniseffing** [cdjackson/HABmin2#161]
So I stumbled upon inconsistency regarding the use of postUpdate and sendCommand.
My friend and I were testing HABmin with 2 seperate openHAB 2 instances (which use the same configuration and database) and got different results when creating the following rule:
![rule](https://cloud.githubusercontent.com/assets/5879568/14783884/ea128ca0-0af2-11e6-9925-d6c7eac7b463.png)

On his system the output looked like this:
![rule2](https://cloud.githubusercontent.com/assets/5879568/14783939/3ca6a58c-0af3-11e6-9985-6a99bf1fc3ab.png)

On **my** system the output was slightly different, HABmin used sendCommand **instead of** postUpdate. 
Our items Rocker and SmartPlugSwitch are both of type Switch and connected to physical devices via aleoncean EnOcean Binding, so "sendCommand" is what we really want.

For further testing, I decided to set up another openHAB 2 instance on my machine with the very same configuration and installed HABmin again, but to my surprise HABmin used "postUpdate" this time around. I tried to figure out the reason for this but came up with nothing.

Can anyone tell me what is going wrong here? Example 2 on the GitHub page uses "sendCommand" too, while Example 1 doesn't.

We are using the latest stable release of HABmin 2 (v0.1.4, 2016-04-10T22:45:48) and openHAB v2.0.0b2

Also: There is another problem with the rule above, see #162 for more information.

**Comment by cdjackson** [comment]
Please try the latest snapshot to see if this works better...

**Comment by cdjackson** [comment]
I believe this is fixed in the latest version. If not, please reopen.
