### ISSUE TITLE
Trying to install Cooper RFWC5 [Updated xml file]

### ISSUE THREAD

**Issue by rgerrans** [cdjackson/HABmin2#163]
@cdjackson So I'm now trying to add my 5 button Cooper scene controller to my OpenHAB setup.  I saw the device list shows it as still needing information.  I tried adding it with the latest build of the ZWave binding but it came in as an unknown device.  I did get the attached xml file.

[node20.zip](https://github.com/cdjackson/HABmin2/files/244364/node20.zip)

Please let me know what other information I can retrieve to help get this device setup in the database.

**Comment by xsnrg** [comment]
I added your XML to the device.  Thanks for attaching it.  If you have access to the database, you can go in and fill out the other details such as configuration parameters.  If you don't have access, sign up on the database website, and let @cdjackson  know.

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/15

**Comment by rgerrans** [comment]
@xsnrg - Thanks.

@cdjackson - I have an account setup under rgerrans if you want to give me submit access I'll add the parameters.

**Comment by cdjackson** [comment]
Done. You should have access now - thanks.

**Comment by rgerrans** [comment]
Thanks

**Comment by rgerrans** [comment]
I now have access, but it doesn't look like these scene controllers have any configurable parameters - http://www.cooperindustries.com/content/dam/public/wiringdevices/products/documents/technical_specifications/advancedtechinfo_V2.pdf  (unless I'm misunderstanding this document)?

**Comment by cdjackson** [comment]
The device does say that it supports the configuration class, so probably (not definitely) it has configuration…

Was the XML from OH1 or OH2? It doesn’t seem to have had any scene classes (at least there are none in the list now).

**Comment by rgerrans** [comment]
@cdjackson Thanks.  I'll keep searching the net and do have a back channel potentially to Cooper that I can use.  I'm happy to try it w/o if it will compile.

The xml was from OH2.  I did notice that the xml took a bit to show up vs. the other switches that I did in the past.

**Comment by cdjackson** [comment]
It may be there’s nothing much to configure, so maybe it’s not worth worrying too much…..

**Comment by rgerrans** [comment]
I've never configured on Vera beyond adding the scenes (though wish there were options for killing scene LED's when setting scene's through the controller, but was never able to find anyway to do so).  Once we get the controller running, may try to see if I can use that backdoor channel to find out if there are any other options.  I'll keep an eye on the device to see when it roles into the nightly and test it out.  Thanks.

**Comment by rgerrans** [comment]
@cdjackson It looks like we are good to go to test the scene controller, someone just needs to review and so it can be included in the next compile.  Is there something I need to do to put it into a review queue?  Thanks.

**Comment by rgerrans** [comment]
@cdjackson As per our exchange on OpenHab Community, here is copy of the xml file (I assumed you wanted it here and not there)
 [node31.zip](https://github.com/cdjackson/HABmin2/files/258350/node31.zip)

**Comment by cdjackson** [comment]
Sorry - the XML doesn't contain what I was expecting to see. Can you please use a recent version of the OH2 binding so that it will add the extra command classes.

**Comment by rgerrans** [comment]
Chris - I had actually tried yesterdays zwave build but it wouldn't load the stick or devices.  I was able to capture a debug file this time to see if you have any insights to what I'm doing wrong
[Zwave debug.zip](https://github.com/cdjackson/HABmin2/files/259392/Zwave.debug.zip).  Thanks.

**Comment by cdjackson** [comment]
I would hazard a guess that you need to upgrade the overall runtime. A couple of weeks back there was a change in ESH that required the binding to be recompiled, and this means you needed to update the binding. I suspect that your system might need to be updated.

**Comment by rgerrans** [comment]
Thanks Chris.   I saw on OH Community that you were having issues with some of the newer snapshots.  Are the latest good to go, or is there one I should use that is stable with Zwave?

**Comment by cdjackson** [comment]
I think it's ok - it's working fine here anyway, but as I said, you need to make sure that you update OH - not just the binding.

**Comment by rgerrans** [comment]
So I updated to today's OH2 snapshot (#292) that I got off CloudBees and I still can't get 5/09 version of the zwave binding (which I got from jfrog) to work.  

Here is the debug log file I captured.  the 4/25 version runs fine.  Any ideas?
[Zwave Debug.zip](https://github.com/cdjackson/HABmin2/files/260473/Zwave.Debug.zip)

TIA

**Comment by rgerrans** [comment]
Ignore my last post.  I just did a clean install and everything seems to be running ok now with the latest OH2, Habmin2, and Zwave.  Once I finish reconfiguring I'll pull the xml

**Comment by rgerrans** [comment]
Ok, here you go.  Here is an xml file from the latest zwave binding.  Thanks.

[node32.zip](https://github.com/cdjackson/HABmin2/files/260587/node32.zip)

**Comment by xsnrg** [comment]
I uploaded the new XML.  @cdjackson will have to take a look at the entry now.  Thanks for the file

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/15

**Comment by cdjackson** [comment]
Thanks Jim. I already updated this yesterday - sorry - I should have posted here.... 

The XML didn't contain any more information. This is probably because the device doesn't report these classes but relies on the device class rather than the NIF. I manually added the scene channel and it should be in todays build - it would be good to see if this helps - I fear it won't change anything as possibly the device class mapping in the code needs updating as well.

**Comment by rgerrans** [comment]
Thanks guys. I'll text the new build and report back.

**Comment by xsnrg** [comment]
> Thanks Jim. I already updated this yesterday

No worries.  Is there any reason it shows both of the times I uploaded and not the time yesterday that you did?  I am guessing because you updated it differently than the mechanism that shows the file upload?

**Comment by cdjackson** [comment]
I didn’t load the XML yesterday. I looked in the file and knew that it wouldn’t help as it didn’t have the info I expected, so I manually added the scene command classes.

I don’t have any ‘secret’ way to load the XML :)

**Comment by xsnrg** [comment]
okay, not secret just "I run the database so have more access in strange and bizarre ways"  :-)

**Comment by cdjackson** [comment]
Nope - none of them either :)

I can manually go in and delete or change things (very occasionally though), but if I load the XML files, it uses the same methods. That’s why sometimes you’ll find I’ve loaded an XML 10 times or something - due to debugging the scripts if there’s an error...

**Comment by rgerrans** [comment]
I just looked and the scene controller is still showing awaiting final review status in the database.  Did it still pull into the latest build or do I need to wait until it goes through as approved before testing?

**Comment by cdjackson** [comment]
It was added a couple of days ago. The only reason it now shows awaiting approval again is because the XML was reloaded to the site, but if you look at the Diff, there's no changes.

**Comment by rgerrans** [comment]
Just installed the latest Zwave binding, and now the device installs!!!  So we are making progress.  Of course now, I'm totally lost how to test.   I tried turning on debug, setting up a basic scene rule with info logging, and also direct association.  Nothing gets recorded in the log files if a button is pushed and the light doesn't stay on after pushing a scene button.

I did find this discussion that @cdjackson was part of but it looks to me like it was OH1 related? - https://community.openhab.org/t/rfwdc-cooper-scene-controller/2748 I did try setting the scenes up as per that thread in an items file to see if it would work, I do see the following in the log file so seems to be doing something (maybe?):

2016-05-15 17:33:43.472 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 38: Controller is ONLINE. Starting device initialisation.
2016-05-15 17:33:43.473 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:device:aa2bf760:node38' changed from ONLINE to OFFLINE
2016-05-15 17:33:43.475 [WARN ] [ding.zwave.handler.ZWaveThingHandler] - NODE 38: Initialising Thing Node...
2016-05-15 17:33:43.476 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 38: Initialising channel zwave:device:aa2bf760:node38:scene_number
2016-05-15 17:33:43.477 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 38: Initialising cmd channel zwave:device:aa2bf760:node38:scene_number
2016-05-15 17:33:43.478 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 38: Initialising poll channel zwave:device:aa2bf760:node38:scene_number
2016-05-15 17:33:43.479 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 38: Initialising state channel zwave:device:aa2bf760:node38:scene_number
2016-05-15 17:33:43.479 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 38: Polling intialised at 1800 seconds - start in 1800000 milliseconds.
2016-05-15 17:33:43.482 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:device:aa2bf760:node38' changed from OFFLINE to ONLINE
2016-05-15 17:33:43.491 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'zwave:device:aa2bf760:node38' has been updated.
2016-05-15 17:34:19.243 [INFO ] [me.event.ItemChannelLinkRemovedEvent] - Link 'Scene_B_Family_Scene1 => zwave:device:aa2bf760:node38:scene_number' has been removed.
2016-05-15 17:34:19.360 [INFO ] [smarthome.event.ItemRemovedEvent    ] - Item 'Scene_B_Family_Scene1' has been removed.
2016-05-15 17:35:02.755 [INFO ] [smarthome.event.ItemAddedEvent      ] - Item 'Scene_B_Family_1' has been added.
2016-05-15 17:35:02.875 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'Scene_B_Family_1-zwave:device:aa2bf760:node38:scene_number' has been added.
2016-05-15 17:37:14.435 [DEBUG] [WaveSerialHandler$ZWaveReceiveThread] - Receive Message = 01 09 00 04 00 22 03 80 03 3F 6F 
2016-05-15 17:37:14.437 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
2016-05-15 17:37:14.439 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 09 00 04 00 22 03 80 03 3F 6F 
2016-05-15 17:37:14.440 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 09 00 04 00 22 03 80 03 3F 6F 
2016-05-15 17:37:14.441 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class=ApplicationCommandHandler[0x04], type=Request[0x00], priority=High, dest=255, callback=0, payload=00 22 03 80 03 3F 
2016

**Comment by cdjackson** [comment]
I think these messages logged at the end are associated with a different node (34).

I don't know the device, so can't really comment too much on what it sends, but if it doesn't send anything (ie nothing is received in the log) then until this changes there's not much we can look at with the binding...

**Comment by rgerrans** [comment]
Chris,

Thanks.  I did go back through the logs and it looks like there is some definite communication going back and forth, but I'm not comfortable enough with the details yet to understand what the log is telling me and if I can use part of it as a trigger.  Log details attached for the Scene Controller.
[Node38 Log.zip](https://github.com/cdjackson/HABmin2/files/266428/Node38.Log.zip)

On a parallel track, I did try to dig in some more to understand what it takes to configure the scene controller to do device-to-device management like it does on my Vera.  From looking at this: https://groups.google.com/forum/#!topic/openhab/hoyKbgoWijM it looks like the binding would have to send back the special associations to create the control groups where it defines each node / dim level associated with each button.  Which it finally dawned on me is what the technical spec is showing - http://www.cooperindustries.com/content/dam/public/wiringdevices/products/documents/technical_specifications/advancedtechinfo_V2.pdf

Is the binding capable of doing this?  Or would I need to go with a 3rd party tool once I associated all the controlled devices with the zwave controller?

I'll see if I can figure out how to enable verbose logging on my Vera and try to capture what it's sending to the scene controller when it configures it with the various associations.

Thanks again for all the help.

**Comment by cdjackson** [comment]
The communications in the log only seems to be the initialisation - I don’t see anything associated with you pressing buttons. That said, since I don’t know the time at which you pressed the buttons, I can’t be sure…
>  From looking at this: https://groups.google.com/forum/#!topic/openhab/hoyKbgoWijM <https://groups.google.com/forum/#!topic/openhab/hoyKbgoWijM> it looks like the binding would have to send back the special associations
> 
You can configure associations in HABmin, but not the scene controller command class, so you’d need to do this manually until it is supported in OH2.

**Comment by rgerrans** [comment]
Thanks Chris.  That was all the communications back and forth when I was trying to test button pushes.  Now that I'm aware of the manual config option to enable device-to-device connection, that's actually my prefered path rather than having to poll the node to look for changes.  So, now that I can at least associate it with the controller I should be able to do the manual config.

I'll mark this as closed and I appreciate all your assistance.

**Comment by DigiArchiver** [comment]
rgerrans have you had success with this device? I would just like the scene number to pass to the item and then a rule. Can't seem to get any events from the keypad presses. It's associated to the controller.

I'm expecting to see something like "Family_Room_Keypad updated to 3"

Feel free to email me if you think you can help. Thanks.

**Comment by rgerrans** [comment]
@DigiArchiver Unfortunately I haven't had time to play with it yet.  What you are looking to do is what Chris was referring to above that it will have to wait until they add the functionality to OH2.  For me, I use mine with scene associations stored on the scene controller which is going to have to require manually configuring it with zensys-tools.  I just haven't had time to spend the 2-3 hours I'm guessing it will take me to learn how to use them yet.  Sorry I can't be of more help.
