### ISSUE TITLE
Request to add FGMS-001 to database

### ISSUE THREAD

**Issue by kravietz** [cdjackson/HABmin2#168]
Looks like yet another iteration of FGMS-001 multisensor, EU version v3.2:

```
NODE 7: Device could not be resolved to a thingType! 010F:0801:1001::3.2
```

**Comment by cdjackson** [comment]
Please load the XML file for this node to the database.

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/328 <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/328>

**Comment by cdjackson** [comment]
It looks like this is in the database. If the problem still exists, then please provide the XML as above.
