### ISSUE TITLE
osx no right to change or copy into fields

### ISSUE THREAD

**Issue by ViperRNMC** [cdjackson/HABmin2#171]
Hi, i am new to openhab2 and habmin2.

I have an strange problem. I have openhab running and can add zwave, hue etc. When i try to edit or add things in habmin2 i can't write something in the fields. Habmin can find the bindings and things. Try to use different browser but no succes.

**Comment by cdjackson** [comment]
Please be clear about exactly what fields you can't updat in the things editor. Possibly provide a picture to make it clear. 

Thanks

**Comment by ViperRNMC** [comment]
Oké make a pic in a moment.

I saw this in de log:
`2016-05-25 11:17:52.531 [ERROR] [org.openhab.ui.habmin               ] - [org.openhab.ui.habmin.designer(3)] bind method [setItemRegistry] not found; Component will fail
2016-05-25 11:17:52.532 [ERROR] [org.openhab.ui.habmin               ] - [org.openhab.ui.habmin.designer(3)] bind method [setItemRegistry] not found
2016-05-25 11:17:52.533 [DEBUG] [org.openhab.ui.habmin               ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.io.rest.RESTResource}`

**Comment by ViperRNMC** [comment]
![picture device independent bitmap 1](https://cloud.githubusercontent.com/assets/18293340/15535001/c8c4dc3e-226b-11e6-9789-576f09f6dca9.jpg)

**Comment by cdjackson** [comment]
This error is only to do with the block editor for rules - not editing things.

**Comment by cdjackson** [comment]
It looks like you have written things in the field? So it is ok?

**Comment by ViperRNMC** [comment]
No, this is doen with paperui, I cant change it with habmin

**Comment by ViperRNMC** [comment]
Also no copy paste actions possible

**Comment by cdjackson** [comment]
What browser do you use? I have tested this on safari Firefox and chrome with no problem and have never heard of this sort of issue so it's strange.

**Comment by ViperRNMC** [comment]
This is with safari 9.1 osx ec

**Comment by cdjackson** [comment]
Ok - I can also see this on the latest Safari. I’d suggest for now to use a different browser - for sure chrome and firefox work fine. It’s strange that the boxes that don’t work in Safari are standard input boxes!

**Comment by ViperRNMC** [comment]
Yes with Chrome it works, strange...

**Comment by cdjackson** [comment]
I've found the problem - it seems to be a css issue. I'll try and post a fix tonight.

**Comment by cdjackson** [comment]
This should be fixed now - it's working here at least...
