### ISSUE TITLE
No unlinking / delete item

### ISSUE THREAD

**Issue by ViperRNMC** [cdjackson/HABmin2#173]
Hi, next issue, try to change things, changing names is going well now but unlinking of deleting items don't work, It says error.

In Paperui i can unlink items in a thing

**Comment by cdjackson** [comment]
Hi,
this seems to work for me. Can you describe exactly what you are doing?

What I assume is that in the thing display, you go to channels and there is a list of channels. I can add, delete, and unlink items from channels, and it works ok without any errors.

What version of OH2 are you using? Is it a recent version?

Cheers
Chris

**Comment by ViperRNMC** [comment]
I use the latest oh2 snapshot.

When i try to add unlink a channel i see sometimes oké, sometimes error, but all the time i dont see it back in my sitemaps. When i try to unlink let say a systemsats memory item i get error

**Comment by cdjackson** [comment]
Are these items created through the UI, or are they specified in text files?

What do you mean by “don’t see it back in my sitemaps”. This shouldn’t change the sitemap - it only unlinks, or deletes and unlinks an item from a channel.

**Comment by ViperRNMC** [comment]
Made by ui

When i link with ui it comes direct in _ default sitemap

**Comment by cdjackson** [comment]
Ok - I’m not sure what else is wrong then, or how to solve it as it’s working fine here on every item I’ve tested. Maybe you can run in the debugger and get the error that might be returned?

**Comment by cdjackson** [comment]
Closing. If this still exists, then please provide further information.
