### ISSUE TITLE
No info in binding

### ISSUE THREAD

**Issue by ViperRNMC** [cdjackson/HABmin2#174]
Another problem, i don't see any info in the binding in habmin, but when i open it in paperui i see everything. Many this problems bigger, because in preferences i also don't see the persistence

**Comment by cdjackson** [comment]
Sorry - I don’t understand what you’re asking for.

**Comment by ViperRNMC** [comment]
![picture device independent bitmap 1](https://cloud.githubusercontent.com/assets/18293340/15608567/f1aa2ce8-241a-11e6-9d73-ae3003beb5b3.jpg)

Picture is saying more then words, everything is empty, but im sure there is something, because its working.

**Comment by cdjackson** [comment]
Hmm - there’s clearly some sort of bug here, but this should be empty for the zwave binding as there is no configuration.

The config in your picture is from other bindings, so something is clearly wrong...

**Comment by cdjackson** [comment]
The configuration is left over from the previous binding that was selected. This will be fixed in the next version - thanks for reporting.
