### ISSUE TITLE
Hadmin Ready to Use?

### ISSUE THREAD

**Issue by lsafelix75** [cdjackson/HABmin2#176]
Hi,

I wondering whether this plugin is fully functional? For some reasons, I can get it to run but most of the features are not functional:
1. Sitemap - does not trigger channel action
2. Scheduler does't see to work
3. Many settings i still see %%KEY_NOT_FOUND%%
4. Dashboard -  i can't create anything. 

Do i miss any important steps? Cheers

**Comment by cdjackson** [comment]
The focus of HABmin development is for OH2, and as such, I focus on the ‘new’ OH2 interfaces, not the old OH1 interfaces. Currently there is no sitemap concept for OH2, no scheduler, rules are experimental etc. So, I am focussing on the new developments only…

> 1. Sitemap - does not trigger channel action
> 
The current sitemap is from OH1 and as such I am not spending time to update it as other parts of HABmin are improved for OH2/ESH integration

> 2. Scheduler does't see to work
> 
As above, this is not something that has been looked at since the scheduler in ESH is still new. It will be added when these interfaces are available.

> 3. Many settings i still see %%KEY_NOT_FOUND%%
> 
Please provide a list - there shouldn’t be any.


> 4. Dashboard - i can't create anything.
> 
Basic functionality should work fine.

**Comment by dbellandi** [comment]
I am using habmin2 0.1.5 with OH2 and I get %%KEY_NOT_FOUND%% errors when:

- Choosing an item in the Charting interface
- Trying to create a new rule
- Dashboards -> New Dashboard -> Add Widget -> Control Group -> Group Properties:  message appears in Group Name dropdown


![image](https://cloud.githubusercontent.com/assets/5230902/15796721/6e628e02-29c9-11e6-9323-db177f91102a.png)

**Comment by ifol** [comment]
I'm using: Version: 0.1.6, 2016-06-05T08:56:54

![key-not found](https://cloud.githubusercontent.com/assets/15725550/15993957/103e5912-30f6-11e6-9138-e4fddaf27e90.png)

After trying to create chart:
![key-not found-charts](https://cloud.githubusercontent.com/assets/15725550/15993965/7a809c54-30f6-11e6-9069-5c8be0d156ab.png)

**Comment by ifol** [comment]
In services also, might there be something wrong with my installation perhaps?

![key-not found-services](https://cloud.githubusercontent.com/assets/15725550/15994062/b2c92e20-30f9-11e6-9974-578d4f7cc009.png)

**Comment by cdjackson** [comment]
I'm going to close this issue since it's now being used for the strings... I think I've already fixed the ones you've listed (or most of them anyway) - I'll provide a new update in the next day or two, and then please open a new issue to report the string problems if needed.

**Comment by cdjackson** [comment]
I've just updated the snapshot if you want to try that.

**Comment by dbellandi** [comment]
They all look fixed except right away when you do:

Chart Editor -> New Chart

Thanks!

**Comment by cdjackson** [comment]
Thanks. I'll try and fix this one tonight and release an updated snapshot.

**Comment by cdjackson** [comment]
Can you provide a picture of where you mean - I’m not sure I know where “New Chart” is?

**Comment by dbellandi** [comment]
Sure:

[image: Inline image 1]

**Comment by dbellandi** [comment]
(It happens right when I click "New Chart" on the left under "Charts")

**Comment by cdjackson** [comment]
Unfortunately github strips pictures when you reply by email (I know - not useful!).

**Comment by dbellandi** [comment]
Ahh, oops!  How's this:

![image](https://cloud.githubusercontent.com/assets/5230902/16058466/4ade86f6-3244-11e6-9278-d57582776def.png)

**Comment by cdjackson** [comment]
Thanks. I think this might mean that you have no persistence services - especially with the yellow exclamation mark at the top…  I’ll see if I can make this display properly.

**Comment by dbellandi** [comment]
Ahh--I haven't set up any persistence services since switching to OH2.

**Comment by mabnz** [comment]
I get KEY_NOT_FOUND on all Things after recently upgrading to OH2 RC1. Have I done something wrong or is this issue still outstanding?

**Comment by cdjackson** [comment]
This is still outstanding - I’ve just not had a chance to look at this as I’m on holiday right now.

**Comment by lsafelix75** [comment]
Is this fixed? I am still seeing them at "Scheduler"
