### ISSUE TITLE
Add to database: Qubino Flush Dimmer 0-10V

### ISSUE THREAD

**Issue by newjoerg77** [cdjackson/HABmin2#177]
Dear all, 
please add the "Qubino Flush Dimmer 0-10V" to the zwave database.
The device is new and different from the "Qubino Flush Dimmer".

Thanks a lot!
In the following the xml file for this device:
[node23.txt](https://github.com/cdjackson/HABmin2/files/296371/node23.txt)

**Comment by cdjackson** [comment]
I've generated the database entry here (http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/363). The configuration information will need to be added from the manual - please can you create an account and add this information?

When you create the account, email me and I'll give you edit access.

**Comment by newjoerg77** [comment]
Hello Chris,

thanks for the database entry.
I created an account yesterday. The username is "newjoerg" / email
newjoerg@web.de.

Thanks

Regards,
Jörg

**Comment by cdjackson** [comment]
Hi - I’ve given you write access now. Any problems, just let me know…

**Comment by newjoerg77** [comment]
Hi, I have added the configuration Details. Do I need to do anything else?
As I understand the resulting xml file has to be added to the binding? Can
you do this? That'll be great. Thanks!

**Comment by cdjackson** [comment]
Thanks. I'll take a look tonight hopefully, but yes, I will transfer the XML into the binding as it's an automated export.

**Comment by newjoerg77** [comment]
Great thanks a lot. I installed the new binding and the device is working
well!

**Comment by cdjackson** [comment]
Thanks for the feedback - I'll close...
