### ISSUE TITLE
[setItemRegistry] not found - Items not available in rules editor

### ISSUE THREAD

**Issue by BradyRosino** [cdjackson/HABmin2#181]
I'm trying to figure out why I am unable to select any items in the rules editor. Any help would be greatly appreciated.

If I select the dropdown list from a "get item" element... I only see "item, new variable, rename variable". Should I be seeing an item list here?

I noticed when launching habmin2, I am seeing the following in the logs -

```
07:26:20.166 [ERROR] [org.openhab.ui.habmin               ] - [org.openhab.ui.habmin.designer(167)] bind method [setItemRegistry] not found; Component will fail
07:26:20.167 [ERROR] [org.openhab.ui.habmin               ] - [org.openhab.ui.habmin.designer(167)] bind method [setItemRegistry] not found
```

Seems like it could be related. Let me know if there is anything else I can provide to troubleshoot.

**Comment by cdjackson** [comment]
You can't select items - you need to actually type in the item name at the moment.

**Comment by cdjackson** [comment]
Just to add, I would like to provide a list one day - it just needs to be integrated into the block library so it’s not quite as simple as I would like….
