### ISSUE TITLE
Add to database Eurotronic CometZ

### ISSUE THREAD

**Issue by stadlersamuel** [cdjackson/HABmin2#184]
HI,
Please add to database Eurotronic CometZ. ID 0148:0002:0001:0.5 . Parameters that same as Eurotrinic Stella. http://www.eurotronic.org/en/products/comet-z-wave.html
Thanks

**Comment by cdjackson** [comment]
Do you have the XML file generated by OH2 (in the /userdata/zwave folder)? This is ideally necessary to create the database entry.

**Comment by cdjackson** [comment]
For reference -:
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/database-history/devicesummary/372 <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/database-history/devicesummary/372>

**Comment by stadlersamuel** [comment]
This is that xml:

<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>THERMOSTAT</genericDeviceClass>
    <specificDeviceClass>THERMOSTAT_GENERAL_V2</specificDeviceClass>
  </deviceClass>
  <homeId>0xfd27d083</homeId>
  <nodeId>3</nodeId>
  <version>4</version>
  <manufacturer>0x148</manufacturer>
  <deviceId>0x1</deviceId>
  <deviceType>0x2</deviceType>
  <listening>false</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <security>false</security>
  <beaming>true</beaming>
  <maxBaudRate>40000</maxBaudRate>
  <nodeInformationFrame>
    <commandClass>BASIC</commandClass>
    <commandClass>SWITCH_MULTILEVEL</commandClass>
    <commandClass>SENSOR_MULTILEVEL</commandClass>
    <commandClass>THERMOSTAT_MODE</commandClass>
    <commandClass>THERMOSTAT_SETPOINT</commandClass>
    <commandClass>NODE_NAMING</commandClass>
    <commandClass>BATTERY</commandClass>
    <commandClass>WAKE_UP</commandClass>
    <commandClass>MANUFACTURER_SPECIFIC</commandClass>
    <commandClass>VERSION</commandClass>
  </nodeInformationFrame>
  <supportedCommandClasses>
    <entry>
      <commandClass>THERMOSTAT_SETPOINT</commandClass>
      <thermostatSetpointCommandClass>
        <version>1</version>
        <instances>1</instances>
        <versionSupported>3</versionSupported>
        <setpoints>
          <entry>
            <setpointType>FURNACE</setpointType>
            <setpoint>
              <setpointType>FURNACE</setpointType>
              <initialised>true</initialised>
              <initCount>0</initCount>
              <outer-class reference="../../../.."/>
            </setpoint>
          </entry>
          <entry>
            <setpointType>HEATING</setpointType>
            <setpoint>
              <setpointType>HEATING</setpointType>
              <initialised>true</initialised>
              <initCount>0</initCount>
              <outer-class reference="../../../.."/>
            </setpoint>
          </entry>
        </setpoints>
        <isGetSupported>true</isGetSupported>
      </thermostatSetpointCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <versionSupported>1</versionSupported>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <versionSupported>1</versionSupported>
        <libraryType>LIB_SLAVE_ENHANCED</libraryType>
        <protocolVersion>3.67</protocolVersion>
        <applicationVersion>0.5</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>SENSOR_MULTILEVEL</commandClass>
      <multiLevelSensorCommandClass>
        <version>4</version>
        <instances>1</instances>
        <versionSupported>4</versionSupported>
        <sensors>
          <entry>
            <multilevelSensorType>TEMPERATURE</multilevelSensorType>
            <multilevelSensor>
              <sensorType>TEMPERATURE</sensorType>
              <initialised>true</initialised>
            </multilevelSensor>
          </entry>
        </sensors>
        <isGetSupported>true</isGetSupported>
      </multiLevelSensorCommandClass>
    </entry>
    <entry>
      <commandClass>NODE_NAMING</commandClass>
      <nodeNamingCommandClass>
        <version>1</version>
        <instances>1</instances>
        <versionSupported>1</versionSupported>
        <name>LRTherm.2</name>
        <location>LivingRoom</location>
      </nodeNamingCommandClass>
    </entry>
    <entry>
      <commandClass>THERMOSTAT_MODE</commandClass>
      <thermostatModeCommandClass>
        <version>1</version>
        <instances>1</instances>
        <versionSupported>3</versionSupported>
        <modeTypes>
          <modeType>OFF</modeType>
          <modeType>MANUAL</modeType>
          <modeType>HEAT</modeType>
          <modeType>HEAT_ECON</modeType>
        </modeTypes>
        <isGetSupported>true</isGetSupported>
      </thermostatModeCommandClass>
    </entry>
    <entry>
      <commandClass>WAKE_UP</commandClass>
      <WakeUpCommandClass>
        <version>2</version>
        <instances>1</instances>
        <versionSupported>2</versionSupported>
        <targetNodeId>1</targetNodeId>
        <interval>240</interval>
        <minInterval>240</minInterval>
        <maxInterval>15728400</maxInterval>
        <defaultInterval>604672</defaultInterval>
        <intervalStep>240</intervalStep>
        <lastWakeup>2016-06-17 08:20:36.493 UTC</lastWakeup>
        <isGetSupported>true</isGetSupported>
      </WakeUpCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <versionSupported>1</versionSupported>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>SWITCH_MULTILEVEL</commandClass>
      <multiLevelSwitchCommandClass>
        <version>3</version>
        <instances>1</instances>
        <versionSupported>3</versionSupported>
        <isGetSupported>true</isGetSupported>
      </multiLevelSwitchCommandClass>
    </entry>
    <entry>
      <commandClass>BATTERY</commandClass>
      <batteryCommandClass>
        <version>1</version>
        <instances>1</instances>
        <versionSupported>1</versionSupported>
        <batteryLevel>100</batteryLevel>
        <batteryLow>false</batteryLow>
        <isGetSupported>true</isGetSupported>
      </batteryCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
        <versionSupported>1</versionSupported>
      </manufacturerSpecificCommandClass>
    </entry>
  </supportedCommandClasses>
  <securedCommandClasses/>
  <nodeNeighbors>
    <int>1</int>
  </nodeNeighbors>
  <lastSent>2016-06-17 08:20:37.82 UTC</lastSent>
  <lastReceived>2016-06-17 08:20:37.161 UTC</lastReceived>
</node>

**Comment by stadlersamuel** [comment]
In that reference after login is error "You are not authorised to view this resource." And here is that xml file
https://uloz.to/x9QwR6i7/node3-xml

**Comment by cdjackson** [comment]
Ah - I gave you a link that I got to though the admin interface. Sorry... You should be able to find it in the list.

Anyway, I'll look to load the XML and then I should be able to add it to the binding tonight...

Thanks

**Comment by cdjackson** [comment]
This should be in tomorrows binding. Please let me know if it's ok...

**Comment by stadlersamuel** [comment]
Hi,
It is working. Thank you.

**Comment by cdjackson** [comment]
Thanks.
