### ISSUE TITLE
Add to zwave database: GE dimmer 45607

### ISSUE THREAD

**Issue by robschoon** [cdjackson/HABmin2#187]
Please add the GE dimmer to the database. Details attached
[Add GE 45607.pdf](https://github.com/cdjackson/HABmin2/files/333798/Add.GE.45607.pdf)

**Comment by cdjackson** [comment]
Please provide the XML file for this device - it’s created automatically by OH2 and is in the userdata/zwave folder.

**Comment by robschoon** [comment]
Here it is
[node5 xml GE 45607.pdf](https://github.com/cdjackson/HABmin2/files/333803/node5.xml.GE.45607.pdf)

**Comment by robschoon** [comment]
Sorry, this is the wrong node, correct one in a minute

**Comment by robschoon** [comment]
This should be it, sorry for sending a binary switch that is already in the database
[node6 xml GE 45607.pdf](https://github.com/cdjackson/HABmin2/files/333806/node6.xml.GE.45607.pdf)

**Comment by cdjackson** [comment]
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/377

Are you using OH1 or OH2?

**Comment by robschoon** [comment]
Many thanks. I use OH2, just started. Installed on raspberry PI. So far the binary switches are fine. One plugin dimmer is a bit strange, but will look into it next week. The wall dimmers don't work yet, I will try with the updated database. I have still a lot of devices to add and test, they are now on an ADT iHub (Pulse).

**Comment by cdjackson** [comment]
Ok - thanks. I’ll get this added to the binding tomorrow (i.e. it will hopefully be in Tuesdays binding).

**Comment by robschoon** [comment]
OK great, any action needed on the long descriptions? They were just copied from GE's "dimmer.xml".

**Comment by cdjackson** [comment]
Well, it would be good to improve them, but it’s not necessary. If you want to update them it would be appreciated if you have an account?

**Comment by robschoon** [comment]
OK, will have a go when I have a spare moment. First time is most tedious - after that it becomes routine.

**Comment by cdjackson** [comment]
You can edit straight into the database (I’m not sure if you were thinking about editing the XML but I can’t now reload that).

**Comment by robschoon** [comment]
I'll do it straight into DB using eclipse

**Comment by robschoon** [comment]
I will not yet venture into updating anything directly yet. In any case I don't have the privilege (yet) for it.
When will this be available in the openhab 2 release?

**Comment by robschoon** [comment]
These work fine now, thanks
