### ISSUE TITLE
Update in zwave database: Trane_TZEMT400BB32MAA thermostat

### ISSUE THREAD

**Issue by robschoon** [cdjackson/HABmin2#189]
This thermostat installs as node 7. No channels show up. The Database entry shows info incomplete.
Link to the manual is: http://www.zwaveproducts.com/product-documentation/Trane_TZEMT400BB32MAA_manual.pdf 
XML from openhab 2 attached
[node7-trane.xml.pdf](https://github.com/cdjackson/HABmin2/files/337969/node7-trane.xml.pdf)

**Comment by robschoon** [comment]
xml as text file
[node7-trane.txt](https://github.com/cdjackson/HABmin2/files/339761/node7-trane.txt)

**Comment by cdjackson** [comment]
I’ve loaded the xml for this device.

**Comment by robschoon** [comment]
Thanks, will get over the weekend. I'll let you know how it goes.

**Comment by robschoon** [comment]
get=test

**Comment by robschoon** [comment]
This one works fine too.
