### ISSUE TITLE
Add to zwave database: Intermatic Thermostat CA8900

### ISSUE THREAD

**Issue by robschoon** [cdjackson/HABmin2#190]
This doesn't get picked up from database: (0005:4341:8900:4.90) Unknown Device
Manual: https://www.smarthome-products.com/productspecs/CA8900-Instructions.pdf
XML from openhab 2 attached
[node8-intermatic.xml.pdf](https://github.com/cdjackson/HABmin2/files/337998/node8-intermatic.xml.pdf)

**Comment by cdjackson** [comment]
Can you either provide the XML as a text file, or a PDF that doesn’t have page titles as I can’t easily cut and paste… Or, preferably, you can load it straight into the database would be even better :)

**Comment by robschoon** [comment]
If there is an instruction somewhere on how to do that, I will try. Do you need to authorize me?
Anyway, now first the text files
[node8-intermatic.txt](https://github.com/cdjackson/HABmin2/files/339755/node8-intermatic.txt)

**Comment by robschoon** [comment]
This looks useable in the database, when will in be available in the nightly build?

**Comment by cdjackson** [comment]
Sorry - I missed this. No-one seems to have requested the approval so I don’t get notification that it needs to be added.

**Comment by robschoon** [comment]
Must be my problem: it said approved on my screen and the request button had disappeared, so I thought that was it.

Best regards
Rob

**Comment by cdjackson** [comment]
No worries - I’ll add it tonight.

**Comment by robschoon** [comment]
Works fine now
