### ISSUE TITLE
Add to zwave database: RCS Model TZ43 ZWave Thermostat

### ISSUE THREAD

**Issue by robschoon** [cdjackson/HABmin2#191]
And this is the last one of my thermostats:
Manual (with a detailed zwave section). This thermostat looks the same as the Trane thermostat and is functionally very similar. Documentation at http://www.homeseer.com/pdfs/TZ43.pdf
[node9-RCS.xml.pdf](https://github.com/cdjackson/HABmin2/files/338024/node9-RCS.xml.pdf)

[RCS TZ43.pdf](https://github.com/cdjackson/HABmin2/files/338020/RCS.TZ43.pdf)

**Comment by robschoon** [comment]
XML as text 
[node9-RCS.txt](https://github.com/cdjackson/HABmin2/files/339762/node9-RCS.txt)
file

**Comment by cdjackson** [comment]
Added -:
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/380#overview <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/380#overview>

It probably needs configuration information adding still, but I’ll add it to the binding tomorrow.

**Comment by robschoon** [comment]
This one works fine for me, missing nothing I need!

**Comment by cdjackson** [comment]
Ok, I'll close but just note that there's o configuration, so at some point someone will need to add this if the device needs configuring via zwave.
