### ISSUE TITLE
Interface very lacky / not updating status

### ISSUE THREAD

**Issue by thhart** [cdjackson/HABmin2#193]
I am running openHAB 2.0 with habmin 1.6 on a Raspberry. The interface is very lacky and unresponsive not reflecting the state of items especially during configuring. I can clearly see logs of events in the openHAB but these are either updated very slowly or never shown in the UI. As I am new to openHAB I have difficulties to judge is it openHAB, Raspberry or habmin or UI logic depending on the browser. How can I increase the logging of an installed instance or do I have to dive into the source? How is the UI communicating in general?

**Comment by thhart** [comment]
I am using Z-Wave bindings and currently there seem to be some major problems in openHAB there. Probably this is very related to  the problems I have with the UI.

**Comment by cdjackson** [comment]
For logging, you might be better to ask the question on the openhab forum. You need to use the openhab console to set the debug logging.
The UI should be responsive - are you using an RPi 3, 2, or 1?

**Comment by thhart** [comment]
I can judge where it comes from. So this is invalid.
