### ISSUE TITLE
Ecolink PIR-ZWAVE2: Unknown device, no .xml

### ISSUE THREAD

**Issue by robschoon** [cdjackson/HABmin2#194]
This new out of the box PIR gets accepted by my Z-wave stick (Aeotec Gen 5). It gets discovered by openhab, using habmin 2 (SNAPSHOT), but without any identification other than "Z-Wave Node 37 Unknown Device". There is no node37.xml and the rest API (see below) gives nonsensical device ID, manufacturer ID etc and no channels. Any ideas? or do I need to send this PIR back due to a hardware problem? Without the manufacturing ID or Type etc I can't match it to the database!
{
    "statusInfo": {
      "status": "ONLINE",
      "statusDetail": "NONE"
    },
    "label": "Z-Wave Node 37",
    "bridgeUID": "zwave:serial_zstick:155bd4f0c31",
    "configuration": {},
    "properties": {
      "zwave_class_basic": "ROUTING_SLAVE",
      "zwave_class_generic": "BINARY_SENSOR",
      "zwave_deviceid": "2147483647",
      "zwave_frequent": "false",
      "zwave_nodeid": "37",
      "zwave_version": "0.0",
      "zwave_listening": "false",
      "zwave_routing": "true",
      "zwave_beaming": "true",
      "zwave_class_specific": "ROUTING_SENSOR_BINARY",
      "zwave_manufacturer": "2147483647",
      "zwave_devicetype": "2147483647"
    },
    "UID": "zwave:device:155bd4f0c31:node37",
    "thingTypeUID": "zwave:device",
    "channels": []
  }
]

**Comment by cdjackson** [comment]
Please provide a debug log file and I’ll take a look. Enabled debug logging and restart the binding - wake up the device a few times and send me the log...

**Comment by robschoon** [comment]
Thanks for your prompt response. I bought 2 new PIR's, exactly the same make and type and both of these get found in the database and install without issue. Sending the other one back due to hardware issue!
