### ISSUE TITLE
About the z-wave database

### ISSUE THREAD

**Issue by acseven** [cdjackson/HABmin2#197]
This isn't the proper place to put this, but I just wanted to let the author know that the Export button of the z-wave database site isn't working with Google Chrome (works with Firefox though), Mac OS X. The dropdown appears, but there's no apparent trigger after
Cheers
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/

**Comment by cdjackson** [comment]
I use chrome on a Mac normally and it works fine so this is a bit strange. Can you provide any more info?  Is this just oh2 export, or all options on the list?

**Comment by acseven** [comment]
None of the buttons work, actually ("Device List" and "Export" > "..."). I'm attaching what I'm seeing on the Inspector. It could something on my side, but I couldn't say what... 

<img width="741" alt="scrn" src="https://cloud.githubusercontent.com/assets/1176371/17214370/7e465952-54d0-11e6-9204-2d35a0580bca.png">

**Comment by cdjackson** [comment]
So it looks like chrome is blocking the JavaScript files - or at least one of them - the heat map file. This is a joomla file and not loading this is preventing things working.

**Comment by acseven** [comment]
Ah, you're right. It's the only file that my ad blocker is filtering out (I'm using uBlock). By disabling it the buttons works just fine. 
Thanks for the pointer
