### ISSUE TITLE
Latest Habmin2 jar files are missing

### ISSUE THREAD

**Issue by xsnrg** [cdjackson/HABmin2#200]
Hi Chris, not sure if a build error or what happened, but the target folder is empty.  Neither the jar or the apk are there.  I see 2 days ago there was a commit to move to a new build (maven).  Likely the culprit.

**Comment by cdjackson** [comment]
Hi Jim,
Yes, I removed the files from the build. Once I sort the final couple of errors in the build out then we should be moving the repo so that HABmin can be installed directly from openhab. Should be sorted in the next day or two...
