### ISSUE TITLE
Support for z-wave in HABmin2 when using OpenHAB2

### ISSUE THREAD

**Issue by grzech1983** [cdjackson/HABmin2#25]
Hello,

just like you've suggested I'm adding request/issue for adding support for z-wave configuration in HABmin2 when it is used with OpenHAB2.

Thanks

**Comment by cdjackson** [comment]
This should now be implemented. Please try the 0.0.11 snapshot version (in the output folder - not the released version).
I've not tried all functionality yet, so any problems, please let me know.

**Comment by cdjackson** [comment]
Ah - one thing I've forgotten to do is to add a link in the menu - this doesn't work at the moment since the menu swaps from OH1 to OH2 versions depending on what server it detects. Unfortunately here we have an OH1 binding running under an OH2 server, so there's no link. However, just use the Astro binding link (as per your other bug) - it will take you to zwave :)

**Comment by grzech1983** [comment]
So far so good. Actually from latest issues with zwave network some time ago I had no issues with z-wave so I'm not sure if I will be able to catch any errors but it looks like it is working correctly. One more thing about habmin2: where I can find items and sitemaps (I know I can browse sitemap but where I can edit it?) configuration?

**Comment by cdjackson** [comment]
> On 8 Apr 2015, at 12:10, grzech1983 <notifications@github.com> wrote:
> 
> So far so good. Actually from latest issues with zwave network some time ago I had no issues with z-wave so I'm not sure if I will be able to catch any errors but it looks like it is working correctly.
> 
Great - thanks for the feedback. I’ve just pushed a new version of HABmin for OH2 that fixes a couple of small issues (like the zwave link).

> One more thing about habmin2: where I can find items and sitemaps (I know I can browse sitemap but where I can edit it?) configuration?
> 
Not yet implemented. As yet there’s no interface in OH2 to do this - I could implement this in HABmin like I did in OH1, but I’d prefer to do it with the proper interface. Kai started a thread on this in the ESH forum a few weeks back which I replied to, but there’s been no further responses :(

Off topic, but I was wondering if you wanted to translate HABmin2 to Polish (I hope I got your nationality right :) ).

**Comment by grzech1983** [comment]
Yep. I'm from Poland. I'll try making translation. When I finish I will let you know.

When you are mentioning Kai you are talking about this topic:

https://www.eclipse.org/forums/index.php/t/1064113/

?

**Comment by cdjackson** [comment]
> Yep. I'm from Poland. I'll try making translation. When I finish I will let you know.
> 
That's great - thanks :)

> When you are mentioning Kai you are talking about this topic:
> 
> https://www.eclipse.org/forums/index.php/t/1064113/ <https://www.eclipse.org/forums/index.php/t/1064113/>Yep - that’s the one…

Cheers
Chris

**Comment by cdjackson** [comment]
This issue is resolved so closing...
