### ISSUE TITLE
Latest OH2 containing Astro binding 2.0 shows in HABmin2 as zwave configuration panel

### ISSUE THREAD

**Issue by grzech1983** [cdjackson/HABmin2#26]
Hello,

latest OH2 contains Astro 2.0 binding which shows in HABmin2 Configuration dropdown correctly but it points to:

.../habmin/index.html#/binding/zwave

URL.

Regards

**Comment by cdjackson** [comment]
The binding configuration in OH2 isn’t currently implemented (other than for zwave) - the menu for other bindings should be disabled at the moment…

I’ll have a look at this next though - I’m nearly at the point where I can hopefully change my system over to use OH2 which will help with development :)
