### ISSUE TITLE
XML upload, requesting addition of Linear WS15Z-1

### ISSUE THREAD

**Issue by EricCantrell** [cdjackson/HABmin2#27]
Device here -> http://products.z-wavealliance.org/products/1029

XML Below

<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>BINARY_SWITCH</genericDeviceClass>
    <specificDeviceClass>SCENE_SWITCH_BINARY</specificDeviceClass>
  </deviceClass>
  <homeId>0x185126a</homeId>
  <nodeId>3</nodeId>
  <version>4</version>
  <manufacturer>0x14f</manufacturer>
  <deviceId>0x3533</deviceId>
  <deviceType>0x5257</deviceType>
  <listening>true</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <healState>DONE @ 2015-04-10T21:39:23+0000</healState>
  <supportedCommandClasses>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>CONFIGURATION</commandClass>
      <configurationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configParameters/>
      </configurationCommandClass>
    </entry>
    <entry>
      <commandClass>SWITCH_BINARY</commandClass>
      <binarySwitchCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </binarySwitchCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_CONTROLLER_BRIDGE</libraryType>
        <protocolVersion>7.2</protocolVersion>
        <applicationVersion>9.1</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>SCENE_ACTIVATION</commandClass>
      <sceneActivationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </sceneActivationCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>1</int>
    <int>4</int>
    <int>5</int>
    <int>6</int>
  </nodeNeighbors>
  <lastSent>2015-04-10 22:07:13.59 UTC</lastSent>
  <lastReceived>2015-04-10 22:07:13.152 UTC</lastReceived>
  <applicationUpdateReceived>true</applicationUpdateReceived>
</node>

**Comment by EricCantrell** [comment]
I'm still using OpenHab 1.6.2 with HABMin 1, not sure if this is the right way to ask for this device to be added for that...

**Comment by cdjackson** [comment]
> I'm still using OpenHab 1.6.2 with HABMin 1, not sure if this is the right way to ask for this device to be added for that…
> 
It's fine, but can you see if you can find the devices in the pepper1 database (www.pepper1.org/zwave I think).

**Comment by EricCantrell** [comment]
Checked all Linear switches in the db here http://www.pepper1.net/zwavedb/ ... found my Dimmer that you already had, but not the WS15Z-1

**Comment by EricCantrell** [comment]
Accidentally hit close and comment,oops.  reopened.

**Comment by EricCantrell** [comment]
Not sure if it's at all helpful, but I did find the Manual http://www.nortekcontrol.com/pdf/manuals/WS15Z1_manual.pdf

**Comment by cdjackson** [comment]
Yep - that’s fine - I should be able to use that - thanks…

I’ll try and do it over the weekend...

**Comment by EricCantrell** [comment]
No rush, just found this http://www.homeseer.com/compare-z-wave-dimming-wall-switches.html and it looks like it doesn't support associations, which was my aim.

**Comment by cdjackson** [comment]
Why do you want associations - what do you actually want to do? I suspect the scene class might also do what you want, although they aren't fully implemented.

**Comment by cdjackson** [comment]
This has been added to the database - it should be in tomorrows snapshot.

**Comment by EricCantrell** [comment]
Regarding associations: I was hoping to set it up such that if I double click or triple click on a switch, that it will control other lights.  Hoping to set one up such that I come down my stairs, double click it, and all 4 first floor light switch on.  Triple click to turn the basement lights on.

I've got some scene-like behavior set up on my web/phone console but my wife is averse to such things, and she wants something she can do at the switch.

I haven't fully digested what everything does, so it's possible I'm misunderstanding associations (and I don't yet fully grasp the scene class).  Most of my experience thus far is just setting up groups and rules in OpenHab.
