### ISSUE TITLE
XML upload, requesting addition of GE Dimmer

### ISSUE THREAD

**Issue by EricCantrell** [cdjackson/HABmin2#28]
Dimmer -> http://www.amazon.com/gp/product/B006LQFHN2

XML Below

<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>MULTILEVEL_SWITCH</genericDeviceClass>
    <specificDeviceClass>POWER_SWITCH_MULTILEVEL</specificDeviceClass>
  </deviceClass>
  <homeId>0x185126a</homeId>
  <nodeId>8</nodeId>
  <version>4</version>
  <manufacturer>0x63</manufacturer>
  <deviceId>0x3031</deviceId>
  <deviceType>0x4944</deviceType>
  <listening>true</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <supportedCommandClasses>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>CONFIGURATION</commandClass>
      <configurationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configParameters/>
      </configurationCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_CONTROLLER_BRIDGE</libraryType>
        <protocolVersion>7.0</protocolVersion>
        <applicationVersion>6.5</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>SWITCH_MULTILEVEL</commandClass>
      <multiLevelSwitchCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </multiLevelSwitchCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>1</int>
    <int>4</int>
    <int>5</int>
    <int>6</int>
  </nodeNeighbors>
  <lastSent>2015-04-10 22:07:18.14 UTC</lastSent>
  <lastReceived>2015-04-10 22:07:18.39 UTC</lastReceived>
  <applicationUpdateReceived>true</applicationUpdateReceived>
</node>

**Comment by EricCantrell** [comment]
I'm still using OpenHab 1.6.2 with HABMin 1, not sure if this is the right way to ask for this device to be added for that...

**Comment by EricCantrell** [comment]
Looking for this in the  http://www.pepper1.net/zwavedb/ database ... not having any luck finding anything by GE there... arg.

**Comment by cdjackson** [comment]
GE products are manufacturered by JASCO and listed as such in the database. I'm not 100% sure which product is yours though - from the part number on the Amazon link I can't quite tie it up with the database. We also have both dimmers from the pepper database in the openhab database, so yours might be different, but it's probably got the same or similar config.

Can you have a look at the JAsco products in the pepper database and let me know what one you think is yours (if any).

**Comment by EricCantrell** [comment]
So, looking in the pepper database, it doesn't physically resemble either of those JASCO dimmers.  It does, however, look like the switch mentioned here http://www.pepper1.net/zwavedb/device/262 (though it's definitely a dimmer).

Looking through the manual, it's referred to as a ZW3005, whereas those dimmers pepper calls ZW3003.  It's also referred to as 12724, which is what Habmin sees it as now that I updated to 1.7 (specifically "12724 Lighting Control Dimmer Switch").

I did find it on Jasco's website here http://jascoproducts.com/products/ge-z-wave-wall-smart-dimmer
Link to the manual is at the bottom of the page, if that's helpful.

As with the WS15Z-1 that you're also helping me with, my focus was on associations.  Now that it looks like associations aren't supported by this device, I may already have everything I need.

**Comment by cdjackson** [comment]
I've named this the ZW3003 - I hope it's ok...

**Comment by EricCantrell** [comment]
Looks great, i'll test it out ASAP, thanks! :)

**Comment by EricCantrell** [comment]
I've downloaded the ZWave Addon for 1.8.0 and it now sees my office switch as the ZW3003.

I did manage to snag a few switches that DO support associations and that you already have in the database, and will hook them up to see if associations do what I think they do soon. :)

**Comment by cdjackson** [comment]
Great - thanks. I'll close this.
