### ISSUE TITLE
habmin2 not working in Internet explorer 10 -11

### ISSUE THREAD

**Issue by topper2830** [cdjackson/HABmin2#30]
dear chris,

thnx already providing a great layout but I have a few questions concerning habmin 2
I installed as suggested and had to change also the rights as I read before but.
when I open the link in internet explorer I just get a black screen with some icons but can't do anything.
when I open in google chrome , it seems to work perfectly.
can you tell me why ?
I run latest openhab 1.7 snapshot
and the latest habmin & habmin 2
strange part is that habmin 1 works perfectly in internet explorer ?

kind regards

**Comment by cdjackson** [comment]
Hmmm - you're right :) It looks like SSE isn't supported on IE (at least the IE I have here at work). If SSE doesn't work, then you'll have a problem with OH2 since SSE is used for most communications between the server and UI... Maybe there's a shim we can use... I'll take a look...

**Comment by cdjackson** [comment]
http://caniuse.com/#feat=eventsource

This shows no version of IE currently supports SSE/EventSource which probably means no OH2 GUI will work with IE without some sort of additional software (which at least a quick web search hasn't revealed).

**Comment by topper2830** [comment]
true , for now i'm using chrome, but still it does not do what habmin 1 does.
mind that i'm using OPENHAB 1.7 and not OH2
In habmin 1 all works perfectly but in habmin 2 icons do not appear, charts work slow , items cannot be added to gauges and .... any idea what i'm doing wrong ?

**Comment by cdjackson** [comment]
I'm not sure - but note that HABmin2 is targetted toward OH2 so some stuff like editing items simply won't work as the interfaces on OH2 are different.

In HABmin2, icons are done differently - currently they are implemented as pictogram vector fonts that scale nicely, and change colour depending on the theme and context. These are currently defined within HABmin. This works if you use 'standard' icons, but if you have a load of custom icons, then they won't be displayed. The idea is in the longer term to make this configurable, but it's not how it currently works.

I'm not sure what you mean about the 'items cannot be added to gauges' - what happens? You add a gauge, click on the gauge properties, then what?

**Comment by topper2830** [comment]
ok that clears some parts up , although I don't have custom icons, maybe something you may wanna look into.
for the gauges I can't select an item , no dropdown box or anything , just stays blank.

kind regards

**Comment by cdjackson** [comment]
Can you provide a screenshot of the gauge configuration dialog? This all works fine in my system under both Chrome and Firefox.

Likewise with the icons - I get the icons work in most instances. Are you getting any at all, or is it just some that aren't working as I'm sure I haven't got all icons mapped.

**Comment by cdjackson** [comment]
For the IE problem, I hope this will be fixed in the next version (ie tonight I hope). I've now added a pollyfill that hopefully provides the EventSource functionality, but can't currently test this as I'm running a Mac.

**Comment by cjmurph** [comment]
@cdjackson I have the same problem, here's a screenshot. Same in chrome and firefox. I'm not convinced I haven't missed something though.

![gauge_properties](https://cloud.githubusercontent.com/assets/2868949/15446565/d30e4692-1f57-11e6-98cb-fda6fe1b2aa8.png)

under configuration, I have no bindings listed, all my items are there but all are read only.

**Comment by cdjackson** [comment]
That sounds correct. What version of OH2 are you using? If you say this occurs in all browsers then how can it be related to IE only?

The focus on Habmin at the moment has been to get thing configuration running so items are only edited through the thing interface.
