### ISSUE TITLE
HABmin2 with openHAB2

### ISSUE THREAD

**Issue by machinex** [cdjackson/HABmin2#32]
Hi,

I am new to openHAB. I just started experimenting with it. I can't seem to install HABmin2. I've also tried it with openHAB1 but couldn't make it work. I have cloned the OH1 master and put the habmin and zwave jar in the addons folder. Also have put the habmin folder in /distribution/openhabhome/webapps/ directory. Then when i go to http://localhost:8080/habmin/, i see the interface (See the screenshot) but all of the tabs are empty. Also i see the following error in the browser console - 

failed to load resource: the server responded with a status of 404 (ProxyServlet: /services/habmin/config/rules/model/list)
http://localhost:8080/services/habmin/config/persistence/services?_dc=1430932585976 Failed to load resource: the server responded with a status of 404 (ProxyServlet: /services/habmin/config/persistence/services)
http://localhost:8080/services/habmin/persistence/charts?_dc=1430932585979 Failed to load resource: the server responded with a status of 404 (ProxyServlet: /services/habmin/persistence/charts)
http://localhost:8080/services/habmin/persistence/items?_dc=1430932586003 Failed to load resource: the server responded with a status of 404 (ProxyServlet: /services/habmin/persistence/items)
http://localhost:8080/services/habmin/config/icons?_dc=1430932586004 Failed to load resource: the server responded with a status of 404 (ProxyServlet: /services/habmin/config/icons)
http://localhost:8080/services/habmin/config/designer?_dc=1430932586005 Failed to load resource: the server responded with a status of 404 (ProxyServlet: /services/habmin/config/designer)
http://localhost:8080/services/habmin/config/bindings?_dc=1430932586006 Failed to load resource: the server responded with a status of 404 (ProxyServlet: /services/habmin/config/bindings)
http://localhost:8080/services/habmin/config/sitemap?_dc=1430932586006 Failed to load resource: the server responded with a status of 404 (ProxyServlet: /services/habmin/config/sitemap)
http://localhost:8080/services/habmin/config/items?_dc=1430932586005 Failed to load resource: the server responded with a status of 404 (ProxyServlet: /services/habmin/config/items)
http://localhost:8080/services/habmin/bundle?_dc=1430932586006 Failed to load resource: the server responded with a status of 404 (ProxyServlet: /services/habmin/bundle)

Also i notice that the online status is offline. I don't know what am i doing wrong. Next i tried with openHAB2 with HABmin2. The instruction said only to put the jar file in the addons directory as there is no webapps directory. If i go to http://localhost:8080/habmin/index.html i see a 404 error. Again i am stuck. Could you please help me how can i fix this?

![selection_002](https://cloud.githubusercontent.com/assets/8885505/7499132/9e0857b6-f3f3-11e4-8e61-d95f2d6b1b6b.png)

**Comment by cdjackson** [comment]
Hi,
The picture you’ve attached is from HABmin 1 - not HABmin 2 so I’m a little confused.

You say you’re cloning the repositories - are you then running this in Eclipse. If you’re closing the repo, the you’re setting up for development, and my instructions are more related to a ‘production’ installation (i.e. not from source, but actually running OH). If you’re trying to run this in Eclipse, then there’s a whole load of different stuff you need to do.

Please can you advise how you’re running this - is it a cloned repo, and your running in Eclipse, or have you installed the OH (1 or 2?) runtime?

Chris

**Comment by machinex** [comment]
​I have attached the habmin1 screenshot as habmin2 shows 404 error. I am
running the environment from source, which is from eclipse. I am trying to
run both openhab 1 and 2 from eclipse not the runtime version.

Thanks
Sajjad​

On Wed, May 6, 2015 at 1:49 PM, Chris Jackson <notifications@github.com>
wrote:

> Hi,
> The picture you’ve attached is from HABmin 1 - not HABmin 2 so I’m a
> little confused.
>
> You say you’re cloning the repositories - are you then running this in
> Eclipse. If you’re closing the repo, the you’re setting up for development,
> and my instructions are more related to a ‘production’ installation (i.e.
> not from source, but actually running OH). If you’re trying to run this in
> Eclipse, then there’s a whole load of different stuff you need to do.
>
> Please can you advise how you’re running this - is it a cloned repo, and
> your running in Eclipse, or have you installed the OH (1 or 2?) runtime?
>
> Chris
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cdjackson/HABmin2/issues/32#issuecomment-99551363>.
>



-- 
===============================
H M Sajjad Hossain
Graduate Research Assistant
Mobile & Pervasive Computing Lab
University of Maryland Baltimore County
http://userpages.umbc.edu/~hmsajja1/
(443) 825-8341
===============================

**Comment by cdjackson** [comment]
Ok - so if you’re running in Eclipse, then you need to put it in the OH folder, and then import it into Eclipse. Then go to the debug configurations and mark it to start. You also need to add the zwave JAR and do the same thing. I think that will work, but I’ve never tried to do exactly what you’re doing…

**Comment by machinex** [comment]
Sorry i am very very new to openhab. Could you be more specific.

Are you suggesting to put the habmin source or the jar file in the openhab
folder or /distribution/openhabhome/webapps folder in openhab 1? And from
the debug configurations->plugins tab i select the plugin to make it launch
with start?

Thanks
Sajjad

On Wed, May 6, 2015 at 2:21 PM, Chris Jackson <notifications@github.com>
wrote:

> Ok - so if you’re running in Eclipse, then you need to put it in the OH
> folder, and then import it into Eclipse. Then go to the debug
> configurations and mark it to start. You also need to add the zwave JAR and
> do the same thing. I think that will work, but I’ve never tried to do
> exactly what you’re doing…
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cdjackson/HABmin2/issues/32#issuecomment-99559546>.
>



-- 
===============================
H M Sajjad Hossain
Graduate Research Assistant
Mobile & Pervasive Computing Lab
University of Maryland Baltimore County
http://userpages.umbc.edu/~hmsajja1/
(443) 825-8341
===============================

**Comment by cdjackson** [comment]
If you’re using the JAR, put the JAR into the OH2 folder, and then import it into Eclipse - same for the zwave bundle JAR. You could also use the source in the same way - it’s up to you really...
