### ISSUE TITLE
Request for adding zwave Linear Zwave PIR and TBZ48 thermostat

### ISSUE THREAD

**Issue by xsnrg** [cdjackson/HABmin2#40]
Hi Chris,  I have a request for other zwave devices I have laying around, but I have a question for you.  How can we make adding new devices easier for you and for me (a user in this case) ?

There are .xml files that are generated by the zwave plugin that seem to have a lot of data in them returned from the respective node IDs.  Is it possible to somehow use this XML dynamically with Habmin2 in the future to add to the known DB?  Maybe a page in the zwave configuration section of HABmin2 that allows the needed input?  I just see devices coming out faster and faster, and though you are amazingly fast at turning things around, there are probably other things you would wish to do with your time.

That being said, I have a couple Linear motion detectors here that need configs :)

These come up as 
Linear [ID:203,Type:2002]
They have motion and temperature.
Manual here:  http://www.nortekcontrol.com/pdf/manuals/WAPIRZ_install.pdf

The other device is a thermostat from RCS that comes up as:
Manufacturer:16 [ID:5432,Type:5442]

The thermostat generated a comprehensive xml file under it's node id that I can send you if that will help.  The motion detectors did not generate one.  Neither device is in pepper1

Jim

**Comment by cdjackson** [comment]
> There are .xml files that are generated by the zwave plugin that seem to have a lot of data in them returned from the respective node IDs. Is it possible to somehow use this XML dynamically with Habmin2 in the future to add to the known DB?

Unfortunately this isn't possible for a few reasons. The main one is the information that is really needed in the database is simply only available manually - this is all the configuration information. The binding will actually work fine for most devices without a DB entry - it's this manual information that we really need...

I'll try and add the PIR in the next day or three, however the thermostat I can't do without  a manual (or something that provides the configuration).

**Comment by cdjackson** [comment]
Can you tell me the model or name or something for the thermostat? I'll then at least add this information into the database, and then if/when we find the config information we can add this later...

**Comment by cdjackson** [comment]
Sorry - scrub that request - just noticed the model number is in the title :)

**Comment by xsnrg** [comment]
Looks good Chris, considering the data we have so far.  I would be okay with merging what is here and opening another ticket when more information is found about the thermostat device.  The only other thing I have near term would be the xml file that the binding generated.  It does not sound like that is much help.

Thanks

**Comment by cdjackson** [comment]
Thanks. I’ll merge and close this then. When we find more info, feel free to open another issue…

Cheers
Chris
