### ISSUE TITLE
Zwave serial device 'does not exist' 

### ISSUE THREAD

**Issue by xsnrg** [cdjackson/HABmin2#41]
With OH2 ,this happens on 2 different servers and 2 different USB zwave sticks.  Restarting OpenHAB2 two or three times will usually get it to work, and after that run fine until the next time OH2 is restarted.  The device is always there in /dev, whether ACMx or USBx depending on the stick, and has the correct permissions.

2015-05-21 18:13:50 [INFO ] [.z.internal.ZWaveActiveBinding:325  ] - Update config, port = /dev/ttyACM0
2015-05-21 18:13:50 [INFO ] [.z.internal.ZWaveActiveBinding:330  ] - Update config, healtime = 2
2015-05-21 18:13:50 [INFO ] [.z.internal.ZWaveActiveBinding:393  ] - Update config, masterController = true
2015-05-21 18:13:50 [DEBUG] [.z.internal.ZWaveActiveBinding:282  ] - Initialising zwave binding
2015-05-21 18:13:50 [INFO ] [.service.AbstractActiveService:169  ] - ZWave Refresh Service has been started
2015-05-21 18:13:50 [INFO ] [b.z.i.protocol.ZWaveController:146  ] - Starting Z-Wave controller
2015-05-21 18:13:50 [INFO ] [b.z.i.protocol.ZWaveController:154  ] - Z-Wave timeout is set to 5000ms. Soft reset is false.
2015-05-21 18:13:50 [INFO ] [b.z.i.protocol.ZWaveController:407  ] - Connecting to serial port /dev/ttyACM0
2015-05-21 18:13:50 [ERROR] [b.z.i.protocol.ZWaveController:429  ] - Serial Error: Port /dev/ttyACM0 does not exist

**Comment by cdjackson** [comment]
I'm not really sure what I can do with this. One point (that I'm sure you have covered, but I'll mention it anyway) is that the port names on Linux keep changing (I'm guessing you're using Linux?) every time you plug in the stick. There are ways around this - I've never tried it, but I believe they don't work well, so if you're using the system to make the port names static, this might be an issue...

**Comment by xsnrg** [comment]
I am wondering if it is a timing thing.  I also tried a raspberry pi
(slow), and it doesn't seem to happen there.  The other machines are an i7
and a Xeon server.

**Comment by cdjackson** [comment]
What sort of timing? All the binding does is to open the port  (which is a single call) so I don't know that there's any timing I can change. I run this on an i7 Mac and an AMD Linux server (as well as recently on a BeagleBone Black) and have not had any problem.

One point is that I'm currently running this on OH1 still - I'm trying to get all my main bindings into OH2 now and hope to be in a position to change soon. I don't think that OH1/OH2 should make any difference though since the binding is the same...

I guess there's not something running somewhere that's doing a port scan or anything similar that would mean it's opening the port?

**Comment by xsnrg** [comment]
I looked at this some more and have not found anything.  The only thing that might make my situation different than yours is I have two serial bindings that load and configure back to back.  I have a bunch of insteon devices, and the insteon binding always loads right before the zwave binding.  I should try disabling the insteon binding and see what happens.  It shouldn't have any effect of course.

**Comment by cdjackson** [comment]
Yes - I’d definitely try this - I agree, it shouldn’t matter, however I’m pretty sure this isn’t a standard issue as I have no other reports of this sort of thing so we need to look for the unlikely things...

**Comment by xsnrg** [comment]
I removed the insteon binding, and the zwave binding starts correctly every time I have tried (10 in a row).  Putting the insteon binding back in place, zwave starts correctly maybe 1 out of 4 attempts. On the other servers where I am seeing this, the insteon binding is loaded without any insteon devices or configuration, so I hope you can reproduce it.  I will make a ticket against the insteon binding as well, and reference this one.

**Comment by cdjackson** [comment]
Hmmm - unfortunately it might be an issue with the serial library then - unless the insteon binding is doing some sort of scan where it’s looking for devices on any serial port it can find…

**Comment by cdjackson** [comment]
I can't see in the insteon wiki how to set the port address - is this configured in the openhab.cfg file?

**Comment by xsnrg** [comment]
Correct.  There is a line 
insteonplm:port_0=/dev/ttyUSB0

**Comment by cdjackson** [comment]
I will close this since there's now another issue open on this -:
https://github.com/openhab/openhab/issues/2642
