### ISSUE TITLE
Please add Gen5 Aeon Labs Z-Stick Gen5

### ISSUE THREAD

**Issue by xsnrg** [cdjackson/HABmin2#42]
Hi Chris, here is the line from the binding:

No database entry: Aeon Labs [ID:5a,Type:101]

Everything seems to be operating fine.  I dropped it in place of the older Z-stick S2.  I will share the engineering doc from Aeotec when they have it ready.

The device is called Z-Stick Gen5

Thanks!
Jim

**Comment by cdjackson** [comment]
Ok - this was added a few weeks back - your device has a different 'Type' - I'll add this tonight.

**Comment by cdjackson** [comment]
This should be in the latest snapshot versions. Please advise if it looks ok...

**Comment by xsnrg** [comment]
Confirmed working.  Thank you!
