### ISSUE TITLE
Android: V 0.0.13 / 0.0.14 APKs not working

### ISSUE THREAD

**Issue by cdjackson** [cdjackson/HABmin2#49]
The Android APK locks at the loading screen.

**Comment by cdjackson** [comment]
The 0.0.15 snapshot in the output folder is now working.

**Comment by xsnrg** [comment]
Also verified working on 5.0 and 4.4.4 tablet.

**Comment by cdjackson** [comment]
Thanks for the feedback. I'm just using this on an old Note2 - I'd welcome any feedback on how responsive it is. It seems ok on my Note, but others tell me that using Codova (the compiler I use to make an APK) will make it run very slow...

**Comment by xsnrg** [comment]
Some of the more complex page generation, such as sitemaps takes a little bit to load.  Not as bad on my Galaxy S5, but my (very) old Xoom shows it.  I wouldn't let that worry you much though. It is amazing this thing still lives.

**Comment by cdjackson** [comment]
Thanks - I guess my Note 2 (which is 3 years old) isn’t doing too bad then… :)
