### ISSUE TITLE
Missing development dependencies

### ISSUE THREAD

**Issue by docbender** [cdjackson/HABmin2#6]
Hi, I tried compile HABmin2. At first I updated dependencies with "npm update". But I still had to install manually following dependencies:
grunt-shell, grunt-contrib-compress, grunt-contrib-htmlmin, grunt-ng-annotate, grunt-json-minify, grunt-contrib-cssmin.

**Comment by cdjackson** [comment]
Sorry - I think this should say “grunt install” - I’ll update.

Thanks

**Comment by cdjackson** [comment]
I've updated the package file to (hopefully!) include the missing packages, but just to note that I'm likely to change the build chain a bit more in the coming weeks so there might be another package or two to be added...

**Comment by cdjackson** [comment]
I think this is resolved - I reinitialised my local copy and everything seem to be resolved after install.
