### ISSUE TITLE
In left pane, hovering over item's wave icon shows text partly in German

### ISSUE THREAD

**Issue by corb555** [cdjackson/HABmin2#62]
If I hover over the wave icon in the left pane, it will show elapsed time in German.  For example:  Hovering over the wave next to my first ZWave device displays:
The device is operating and was last seen vor Einer Minute

My language preference is set to English/UK.

I have habmin-1.7.0 installed and habmin2 under webapps (recently installed but not sure how to check version #).

**Comment by cdjackson** [comment]
Thanks for reporting...

You can find the version on the main page (ie at /habmin/index.html). It would be interesting to know if you have the latest version as I recently changed something in this area to add German to the list of languages supported...

Unfortunately I'm changing things around here so can't easily test, but can you try something (maybe you've already done this). Can you go to the window where you select the language, select German or French, then select English and then refresh HABmin. I want to see if it's a default issue - ie German may get loaded last for the time translations an if you don't specifically set it, it might then default to this...

Thanks
Chris

**Comment by corb555** [comment]
HABmin version 0.0.15.19.jun.2015

1. Selected French.   Tooltips and everything appear correctly in French (no German)
2. Selected English.  Tooltips and everything are correct.
3. Restarted Openhab.  Tooltips and everything are correct.
(Repeated steps 1 and 2 but with German.  Again everything is fine)

Looks like it has something to do with the initial install/default if you've never selected language.

**Comment by cdjackson** [comment]
Brilliant - thanks for testing. I suspected that might be it and I’ve now added a default to english when the app starts. Once I get my system back up I’ll test it out...
