### ISSUE TITLE
Cant edit default rules. Save button inactive.

### ISSUE THREAD

**Issue by brutevinch** [cdjackson/HABmin2#66]
OS: Windows(firefox), OS X (Safari)
Save button inactive, can't edit default rules, in terminal(nano) all works fine.
Also can't configure zwave nodes and add names (see screen) also can't edit items.

**Comment by cdjackson** [comment]
> Save button inactive, can't edit default rules, in terminal(nano) all works fine.

Just to be clear, what screen are you using. Currently, HABmin only edits rules through the graphical rule editor.


> Also can't configure zwave nodes and add names (see screen) also can't edit items.

You can't edit items in the zwave screen - there was no screenshot if that's what you intended to attach

**Comment by brutevinch** [comment]
Ok with rules. Sorry for screens....I forget about it 
![2015-06-30 10-47-15 zwave habmin](https://cloud.githubusercontent.com/assets/12526597/8427575/e2c8299e-1f31-11e5-8428-bcc2b0b922c5.png)
![2015-06-30 10-46-45 zwave habmin](https://cloud.githubusercontent.com/assets/12526597/8427576/e32d1688-1f31-11e5-96b6-95e34833d230.png)

**Comment by cdjackson** [comment]
I’m still not sure I understand the problem. The screen dump looks ok isn’t it? If the configuration is not downloaded, then the settings will be empty (like we see). What happens when you change them?

**Comment by brutevinch** [comment]
How i can download configuration? this buttons doesn't works. But the way numbers in config accessible. 
![2015-07-01 09-12-16 window](https://cloud.githubusercontent.com/assets/12526597/8447401/7d0a0e74-1fd1-11e5-8024-fb7b208fdc8d.png)

**Comment by brutevinch** [comment]
Associations - same thing
![2015-07-01 09-15-12 window](https://cloud.githubusercontent.com/assets/12526597/8447418/ea79fe06-1fd1-11e5-99e5-a1ecaf4af99d.png)

**Comment by cdjackson** [comment]
The button just changes the view from network view, to configuration view. The binding should automatically download the configuration data automatically during the initialisation - what version of the binding are you using?

**Comment by cdjackson** [comment]
> On 1 Jul 2015, at 05:16, brutevinch <notifications@github.com> wrote:
> 
> Associations - same thing

Yes - it’s the same. The associations are downloaded also during initialisation so long as you have a new (1.7) version of the binding.

**Comment by brutevinch** [comment]
i use one of last build wave binding from cloudbees. org.openhab.binding.zwave-1.8.0-20150619.071506-19.jar

**Comment by cdjackson** [comment]
Maybe there’s a problem with the device and it’s not initialising correctly? Can you try deleting the XML and restarting the binding.

**Comment by brutevinch** [comment]
Yes of course. After deleting xml and restarting OH2 i get this in logs: http://pastebin.com/dVUQE6G0
Dimming/ON-OFF Light working well.

**Comment by cdjackson** [comment]
Sorry - I should have said that I needed a debug log… That said, it looks like configuration is being requested, but without the debug log it’s hard to say what...

**Comment by brutevinch** [comment]
i went away to openhab1 with habmin1 where is all works.

**Comment by cdjackson** [comment]
Ok, I'll close then for now. If you want to work out the problems here then feel free to open a new request.
