### ISSUE TITLE
Error 403 forbidden

### ISSUE THREAD

**Issue by Henry7** [cdjackson/HABmin2#7]
Hi,

I'm using openhab 1.6.1 on Raspberry Pi, Habmin-Binding SNAPSHOT-1.7.0 and zwave-Binding 1.6.1 installed.

I copied the relevant habmin2-files in the webapps ordner, but when i try to access habmin2, i get

HTTP ERROR 403

Problem accessing /habmin2/. Reason:

    Forbidden

**Comment by cdjackson** [comment]
Im not sure why this would happen. With openhab there shoukd be no security on running an app in the Web apps folder if I remember correctly.  The security is on the rest interface and that should not stop the web interface starting.

Likewise, to just get the web interface showing you dont need the jar files either...

Judt to be clear, you have put the files into a folder /openhab/webapps/habmin2 (assuming that openhab is installed in the openhab folder) and the index file is in this folder?

Also, you are installing the file from the releases link at the top of the Github page, and there in only the index file a few folders and maybe acfew other files in the folder?

**Comment by Henry7** [comment]
Hi,

yes i put the files into the folder /openhab/webapps/habmin2
I downloaded habmin2 through the following URL: https://github.com/cdjackson/HABmin2/archive/master.zip

In this zip file, there is no "index.html" like in Habmin1 - maybe this is the issue?
I'm using a raspberry pi if that matters.

**Comment by cdjackson** [comment]
Yes - this is the problem.
There two options...  Either, using the file you have already downloaded, move the folder ```src``` into the webapps folder.
Or - download the package from the releases folder on Github and delete the file you've already loaded (https://github.com/cdjackson/HABmin2/releases). This is the best option...

The readme isn't clear - I'll try and improve this...

Let me know how it goes...

**Comment by Henry7** [comment]
Hi,

yes I made the stupid mistake and moved all the files and folders from the zip to the webapps folder. (I'm a beginner at linux & openhab)
Thanks for your help!

**Comment by cdjackson** [comment]
No problem - the doc wasn't exactly that clear so hopefully it's improved now :)

**Comment by martinmatias** [comment]
Hi Chris, I'm having the same problem as Henry using habmin 0.1.3. I've moved src directory etc and still getting forbidden. I'm usgin OH 1.8.2 and running OH1 as root.
Also, can habmin1 and habmin2 coexist? Of course I've tried habmin2 without habmin1 without success.
Here is my actual file tree:
webapps directory:

```
cubie@Cubian:/opt/openhab/webapps$ ls
0.1.3.tar.gz  habmin  habmin2  images  master.zip  README  src  static

```
```
cubie@Cubian:/opt/openhab/webapps/habmin2$ ls
bower.json       CHANGELOG.md   CONTRIBUTING.md  Gruntfile.js  module.prefix  openhab2  package.json  src
build.config.js  changelog.tpl  cordova          karma         module.suffix  output    README.md     vendor
```
```
cubie@Cubian:/opt/openhab/addons$ ls
org.openhab.binding.mqtt-1.8.2.jar            org.openhab.io.habmin-1.7.0-SNAPSHOT.jar  org.openhab.ui.habmin_2.0.0.SNAPSHOT-0.1.3.jar
org.openhab.binding.zwave-1.8.0-SNAPSHOT.jar  org.openhab.persistence.rrd4j-1.8.2.jar   README
```


As previously told I've tried without habmin1.
Hope you can help me.
Regards
Martin

**Comment by cdjackson** [comment]
I'm not sure I understand - what `src` directory?  Also, you have both HABmin 1 and 2 JAR files installed - this can't be a good thing!

If you using HABmin2, then only install HABmin 2 -this just requires adding the JAR - nothing else.  Id also suggest opening a separate issue as this is 16 months old and on a very very early version of HABmin2, so I don't think we can imagine its related.

**Comment by martinmatias** [comment]
Hi Cris, thanks for your reply. I've open  issue #156 for this problem. I've also removed habmin1 jar and habmin1 folder. I havent moved /src folder and index.html

Regards
Martin
