### ISSUE TITLE
Most of the functionalities are not working with openhab1

### ISSUE THREAD

**Issue by jamborta** [cdjackson/HABmin2#73]
Hi there,

I am trying to install habmin2 with openhab1, downloaded the zwave and the habmin-1.7.0 dependencies, also added latest release to the webapps folder under habmin2. But when I open the UI, most of the stuff are greyed out, or does not seem to pick up any items (e.g. charts are not working, bindings are listed but without text, Zwave seems to work). Am I missing something?

thanks,

**Comment by cdjackson** [comment]
Many things are still being developed, or are not applicable under OH1 - most of the configuration menu for example is only applicable under OH2. However, it’s hard to say if this answers your question…

**Comment by jamborta** [comment]
thank you. what about the charting, should that work? (on mine it comes up empty)

**Comment by cdjackson** [comment]
Yes - charting should work. What do you mean by ‘empty’? Blank screen or what? Maybe there’s an exception being thrown… Can you send me a screenshot?

Actually, please also confirm that you have the HABmin1 JAR file installed, plus also the zwave JAR file. Also, make sure that these files are running, and they are the correct length. I often find binary files downloaded off GitHub get corrupted or are aborted during the transfer and are therefore quite short (maybe only 30k or so).

**Comment by jamborta** [comment]
It looks like this.
<img width="1280" alt="screen shot 2015-07-30 at 17 45 20" src="https://cloud.githubusercontent.com/assets/4638229/8989250/d9ea8ccc-36e2-11e5-8d46-9577428ad49b.png">

I have two jars added:
org.openhab.io.habmin-1.7.0-SNAPSHOT.jar - size: 1120026
org.openhab.binding.zwave-1.8.0-SNAPSHOT.jar - size: 1134175

**Comment by cdjackson** [comment]
File sizes look about right. The screen looks like it’s loaded ok, but I’d suspect that the JAR isn’t running for some reason. Does HABmin1 work?

**Comment by jamborta** [comment]
yes, habmin1 works fine.

**Comment by jamborta** [comment]
seems that after a few restarts, it got resolved. thanks for the help.
