### ISSUE TITLE
habmin2 not detected by openhab2

### ISSUE THREAD

**Issue by airix1** [cdjackson/HABmin2#76]
Running the latest version of openhab2 (2.0.0 snapshot from cloudbees) and habmin2 is not detected.  Made sure the habmin2 jar is the right size (just under 3megs).  Nothing shown in the debug log.

**Comment by cdjackson** [comment]
Is the zwave binding running ok?

**Comment by airix1** [comment]
Sorry, failed to rtfm.  Working now.  Thanks for the help!

**Comment by cdjackson** [comment]
No probs :)
