### ISSUE TITLE
Error saving charts and getting list of charts

### ISSUE THREAD

**Issue by Togeole** [cdjackson/HABmin2#8]
Hello,

I got the error message below when trying to get list of charts either with org.openhab.io.habmin-1.5.0-SNAPSHOT.jar and org.openhab.io.habmin-1.7.0-SNAPSHOT.jar.
Also, it's not possible to save charts but I think it's linked.
Note that other lists such as items, rules and so on are working well and return the XML.

Any idea why?

URL: http(s)://openhab/services/habmin/persistence/charts

HTTP ERROR 500

Problem accessing /services/habmin/persistence/charts. Reason:

    com.thoughtworks.xstream.converters.ConversionException:  : ParseError at [row,col]:[1,182]
Message: Octet 2 de la séquence UTF-8 à 3 octets non valide. :  : ParseError at [row,col]:[1,182]
Message: Octet 2 de la séquence UTF-8 à 3 octets non valide.
---- Debugging information ----
message             :  : ParseError at [row,col]:[1,182]
Message: Octet 2 de la séquence UTF-8 à 3 octets non valide.
cause-exception     : com.thoughtworks.xstream.io.StreamException
cause-message       :  : ParseError at [row,col]:[1,182]
Message: Octet 2 de la séquence UTF-8 à 3 octets non valide.
class               : java.lang.String
required-type       : java.lang.String
converter-type      : com.thoughtworks.xstream.converters.SingleValueConverterWrapper
wrapped-converter   : com.thoughtworks.xstream.converters.basic.StringConverter
path                : /charts/entries/chart/items/item/label
line number         : 1
class[1]            : org.openhab.io.habmin.services.chart.ChartItemConfigBean
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : java.util.ArrayList
converter-type[2]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
class[3]            : org.openhab.io.habmin.services.chart.ChartConfigBean
class[4]            : org.openhab.io.habmin.services.chart.ChartListBean
version             : 1.4.6

Thanks!

**Comment by cdjackson** [comment]
Can you please send me the file /etc/habmin/charts.xml.

Thanks.

**Comment by cdjackson** [comment]
Can you try the latest version? It will still give an error when loading the existing file (I guess you can convert?) but should now save as UTF-8.

Let me know how it goes.

**Comment by Togeole** [comment]
Yes, it works perfectly now !

Thanks a lot ☺

De : Chris Jackson [mailto:notifications@github.com]
Envoyé : samedi 3 janvier 2015 16:55
À : cdjackson/HABmin2
Cc : Vincent Quintin
Objet : Re: [HABmin2] Error saving charts and getting list of charts (#8)


Can you try the latest version? It will still give an error when loading the existing file (I guess you can convert?) but should now save as UTF-8.

Let me know how it goes.

**Comment by cdjackson** [comment]
Thanks.
