### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by devTechi** [cdjackson/HABmin2#81]
Hi Chris,

I installed todays openhab2 cloudbees version and tried to install your habmin2 as well.

But I can't see anything (habmin-like) in openhab2 dashboard. And urls like server/habmin.index.html or server/habmin2 won't work either.

What I did:
- copied habmin2 jar file to addons folder
- copied unzipped release zip-file to openhab2/webapps/habmin2
- copied habmin1 jar file to addons folder as well as zwave 1.7 file (next to 1.8) because nothing worked

Am I missing something? I always get a 404 message.

Thank you :)

**Comment by xsnrg** [comment]
Hi, not Chris, but the most common problem I have seen is downloading the jar doesn't always go well.  It should be large.  Try this:

```
wget -N --content-disposition --no-check-certificate https://raw.githubusercontent.com/cdjackson/HABmin2/master/output/org.openhab.ui.habmin_2.0.0.SNAPSHOT-0.0.15.jar
```

**Comment by devTechi** [comment]
Thanks :)
Will try

**Comment by devTechi** [comment]
YEAH.
Great thanks @xsnrg 
This did it. After downloading I saw this `[INFO ] [u.h.internal.servlet.HABminApp] - Started HABmin servlet at /habmin`

And I see habmin in dashboard. Do I really need the folder webapps and the io.jar file of version 1.x?

**Comment by devTechi** [comment]
Great! Thank you.
