### ISSUE TITLE
create database automatically 

### ISSUE THREAD

**Issue by volkerrichert** [cdjackson/HABmin2#88]
based on the pepper1 XML it should be possilbe to generate at leats a basic zwave database automatically.

The "Z-Wave Device Library by Pepper-One GmbH is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License"

**Comment by cdjackson** [comment]
Sorry - this won't be implemented. The database will change completely in OH2 so it's just not worth it.

**Comment by volkerrichert** [comment]
How will it looks like in OH2?

**Comment by cdjackson** [comment]
https://github.com/cdjackson/HABmin2/wiki/ZWave-Product-Database---OH2 <https://github.com/cdjackson/HABmin2/wiki/ZWave-Product-Database---OH2>

There will basically be more information required in OH2 so that we can automate the item definitions.
