### ISSUE TITLE
Can't set  z-wave associations / FGMS-001 Motionsensor unknown device on bind

### ISSUE THREAD

**Issue by Philippwolf** [cdjackson/HABmin2#89]
I'm using org.openhab.ui.habmin_2.0.0.SNAPSHOT-0.0.15.jar  + org.openhab.binding.zwave-1.8.0-20150908.070009-74.jar and the latest openhab2-release from cloudbees.
I can correctly control most of my devices using the classic ui and the paperui.

It's possible to click on the parameters and association-nodes but she shut-down menus are empty. The same counts for associations, nothing to select in the dropdown box.

It's the same when setting parameters, some are working, many have nothing to select. It was imposstible to set the parameter 14 of my FGS221 (switch bi/mono)... I solved this Problem using openhab and habmin1 though

-----fixed ----
My last problem is that my Fibaro Motionsensor won't bind correctly.
No node.xml is beeing generated and the Sensor is beeing added as "unknown device".
I already tryed removing and readding the sensor in Habmin2 and Habmin1 several times, also replugged the battery -> always the same "unknown device"
-----fixed ----
/edit -> just checked back and the device is correctly detected now, im happily surprised :)

**Comment by cdjackson** [comment]
This isn't implemented at the moment - it's something I'm working on but it won't be implemented until the OH2 version of the zwave binding is released as the way associations work is not compatible...

I'll close this for now, but feel free to open another issue if there are problems once the zwave 2 version is release (soon I hope!).
