### ISSUE TITLE
knx binding not show

### ISSUE THREAD

**Issue by sebglon** [cdjackson/HABmin2#93]
on habmin2 / configuration / installed binding, i can't show KNX.

I have an item that use KNX and it works;

**Comment by cdjackson** [comment]
Is this an OH2 binding?

**Comment by sebglon** [comment]
Yes i have installed knx addon 2.0  alpha2

**Comment by cdjackson** [comment]
Please can you describe the problem then.

**Comment by sebglon** [comment]
is it normal that I do not find KNX Binding in the Installed Binding on Habmin2

**Comment by sebglon** [comment]
Sorry this is note an OH2.
