### ISSUE TITLE
Getting 404 Error When Trying to Install

### ISSUE THREAD

**Issue by colterwilson** [cdjackson/HABmin2#96]
Sorry I am just starting out and I am trying to install habmin2 for Openhab 1.7. I followed the instructions and keep getting a 404 error. 

HTTP ERROR 404

Problem accessing /habmin2/index.html. Reason:

    ProxyServlet: /habmin2/index.html
Powered by Jetty://

**Comment by cdjackson** [comment]
Is Habmin listed in the dashboard?

**Comment by colterwilson** [comment]
No

Sent from my iPhone

On Nov 6, 2015, at 5:47 AM, Chris Jackson <notifications@github.com> wrote:

Is Habmin listed in the dashboard?

—
Reply to this email directly or view it on GitHub
<https://github.com/cdjackson/HABmin2/issues/96#issuecomment-154401516>.

**Comment by cdjackson** [comment]
Then the JAR is probably not installed, or the zwave Jar isn’t isn’t installed. I would check that the files are downloaded from Github correctly.

**Comment by colterwilson** [comment]
I will load them again.

Sent from my iPhone

On Nov 6, 2015, at 8:08 AM, Chris Jackson <notifications@github.com> wrote:

Then the JAR is probably not installed, or the zwave Jar isn’t isn’t
installed. I would check that the files are downloaded from Github
correctly.

—
Reply to this email directly or view it on GitHub
<https://github.com/cdjackson/HABmin2/issues/96#issuecomment-154433006>.

**Comment by colterwilson** [comment]
I get a 404 when I click I the links for the zwave.jar file from your Readme. Do you have another link?

**Comment by cdjackson** [comment]
Just use the zwave file from the OH1 installation (addons zip file I think - where all the bindings are found).

**Comment by colterwilson** [comment]
is it this file? This si the .jar in my addons folder

org.openhab.binding.zwave-1.8.0-SNAPSHOT.jar

**Comment by cdjackson** [comment]
Yes - so you mean this file is already in the addons folder? If both the zwave and habmin JARs are in the addons folder, make sure they are correctly downloaded (i.e. they have the right file size is a good start).

**Comment by colterwilson** [comment]
Here is the contents of my addons directory:

![screen shot 2015-11-06 at 9 33 46 am](https://cloud.githubusercontent.com/assets/15683843/11002388/a4930318-8469-11e5-9583-363fbd9eb20b.png)

**Comment by cdjackson** [comment]
Something doesn’t look right (if I understand this correctly)… Firstly there is more than 1 copy of both HABmin and ZWave, and secondly the HABmin binding looks way too small (1.1MB). If I look on Github it says it’s 2.9MB… The other strange thing is multiple files seem to have the same size which is strange...

**Comment by colterwilson** [comment]
When I look on github at the binding for version 1 it is 1.1 MB

**Comment by cdjackson** [comment]
Sorry - I was thinking version 2. In any case, you have 2 copies of everything - this will cause big problems (it may or may not be the issue, but it really won’t help).

**Comment by colterwilson** [comment]
I cleared out all of the duplicates and it is still not working. I deleted
all of the folders and reinstalled. Still getting the 404 error.

**Comment by cdjackson** [comment]
Ok - what is in the webapps folder then? Is that all installed ok?

**Comment by colterwilson** [comment]
Here is my folder 
![screen shot 2015-11-06 at 12 55 28 pm](https://cloud.githubusercontent.com/assets/15683843/11007239/ca6f7640-8485-11e5-8699-8ff9d0b99785.png)

**Comment by cdjackson** [comment]
That doesn’t look correct - it looks like it’s missing some folders?

**Comment by colterwilson** [comment]
What folders hsould be there?

**Comment by cdjackson** [comment]
https://github.com/cdjackson/HABmin2/tree/master/src <https://github.com/cdjackson/HABmin2/tree/master/src>

**Comment by colterwilson** [comment]
Sorry what would the wget link be to get the right file. Thanks your for
your help with this sorry I am new to this.

**Comment by cdjackson** [comment]
I don’t tend to use wget so am not familiar with it. Go to the HABmin2 folder (https://github.com/cdjackson/HABmin2 <https://github.com/cdjackson/HABmin2>) - on the right side there’s a DOWNLOAD ZIP button. Download this and copy the ‘src’ folder from the ZIP into the webapps folder.

**Comment by colterwilson** [comment]
Ok so I redid my pi from scratch and it fixed a bunch of issues I was having in general. The only lingering issue is that habmin2 keeps giving me the 404 error. Here is a screen shot of my Directories. Do these files look correct?

![screen shot 2015-11-15 at 4 16 21 pm](https://cloud.githubusercontent.com/assets/15683843/11171734/95f89b7c-8bb4-11e5-8af6-018d8c02dc6e.png)
![screen shot 2015-11-15 at 4 16 52 pm](https://cloud.githubusercontent.com/assets/15683843/11171736/975c5846-8bb4-11e5-9569-360dc913b7ce.png)

**Comment by cdjackson** [comment]
Closing this since the development branch is now merged into master. If the problems persist, please raise another issue.
