### ISSUE TITLE
Z Wave binding add request for D-Link DCH-Z110

### ISSUE THREAD

**Issue by Carolinger** [cdjackson/HABmin2#98]
Manufacturer:264 [ID:e,Type:2]
http://products.z-wavealliance.org/products/1151
[D-Link DCH-Z110_120 manual.pdf](https://github.com/cdjackson/HABmin2/files/33120/D-Link.DCH-Z110_120.manual.pdf)

**Comment by Carolinger** [comment]
Already implemented?

**Comment by cdjackson** [comment]
No - I didn’t think we needed to have the same request in two places? You’ve opened exactly the same request twice...

**Comment by Carolinger** [comment]
Sorry my mistake. My apologize. Was not sure where to put it.
Best Regards!

**Comment by cdjackson** [comment]
No probs - I check many places for these :)
