### ISSUE TITLE
z-wave binding:  Add GE 12727 toggle switch

### ISSUE THREAD

**Issue by xsnrg** [cdjackson/HABmin2#99]
This is a simple 120v 60Hz toggle switch:

Manufacturer: GE (found)
ID: 3033
Type: 4952

I have not been able to find a engineering doc for it yet, but will keep searching.  It just works, so have not worried about it.

**Comment by xsnrg** [comment]
It is a GE branded product

https://jascoproducts.com/sites/default/files/product/manuals/12727%20EnFrSp%20QStart%20V1%20081314.pdf

**Comment by xsnrg** [comment]
Found the link for all GE Jasco advanced parameters:

http://www.ezzwave.com/advanced-operation/

**Comment by xsnrg** [comment]
I did the xml, but my dev env is pretty messed up right now it seems.  If somebody else would do the PR, that would be great.

Here is the section to add to the products.xml

```
       <Product>
            <Reference>
                <Type>4952</Type>
                <Id>3033</Id>
            </Reference>
            <Model>12727</Model>
            <Label lang="en">Smart Toggle Switch</Label>
            <ConfigFile>ge/12727.xml</ConfigFile>
        </Product>
```
Here is the ge/12727.xml file:

```
 <?xml version="1.0" encoding="utf-8"?>
<Product>
	<Model>12727</Model>
	<Endpoints>1</Endpoints>
	<Label lang="en">In-Wall Dimmer</Label>
	<CommandClasses>
        <Class><id>0x20</id></Class>
        <Class><id>0x25</id></Class>
        <Class><id>0x27</id></Class>
        <Class><id>0x70</id></Class>
        <Class><id>0x72</id></Class>
        <Class><id>0x86</id></Class>
	</CommandClasses>
	<Configuration>
		<Parameter>
			<Index>4</Index>
			<Type>list</Type>
			<Default>0</Default>
			<Size>1</Size>
			<Label lang="en">Invert switch</Label>
			<Item>
				<Value>0</Value>
				<Label lang="en">ON is top</Label>
			</Item>
			<Item>
				<Value>1</Value>
				<Label lang="en">ON is bottom</Label>
			</Item>
			<Help lang="en"><![CDATA[Set to 1 in the case the switch was installed up-side down.]]></Help>
		</Parameter>
	</Configuration>
</Product>
```

**Comment by xsnrg** [comment]
Can be closed.  Added through the new database entry app.

**Comment by cdjackson** [comment]
Thanks :)

**Comment by knight2000** [comment]
Hello

Reviving this and i apologize if this is not the right way to do it but I'm currently using org.openhab.binding.zwave-1.9.0-SNAPSHOT and trying to add this GE 12727 my openhab debug shows 

[.z.i.config.ZWaveConfiguration:288  ] - NODE 5: No database entry: GE [ID:3033,Type:4952]

Has this not been added to the latest database?

**Comment by cdjackson** [comment]
I’ll add this tomorrow so it should be in Wednesdays binding…
